### ISSUE TITLE
Wrong character's encoding in exported PDF

### ISSUE THREAD

**Issue by jabocrack1** [vsch/idea-multimarkdown#504] opened 2017-10-07 21:14 UTC
Wrong character's encoding in exported PDF (see screenshot). PhpStorm 2017.2.4, installed plugin 2.3.8
on left - acrobat reader with rendered PDF, on right - preview zone with same document.
![screenshot_2](https://user-images.githubusercontent.com/14205678/31311838-7317a190-abbd-11e7-9968-1f2a581e1680.png)

**Comment by vsch** [comment] 2017-10-09 18:55
@jabocrack1, thank you for the report. I will take a look at PDF conversion to see what encoding should be used.

**Comment by cwt9562** [comment] 2018-09-14 02:45
I meet this bug too, any update?

**Comment by Terminator637** [comment] 2018-11-15 18:53
Me too, when it will be fixed?

**Comment by vsch** [comment] 2018-11-15 18:55
@Terminator637, @cwt9562  as soon as I can figure out how to tell the OpenHtmlToPDF to use a different font for the PDF.

The issue is with the font. It does not contain the Unicode characters. Which means that if there is a mix of languages, each one may need to use a different font or have a single font that supports all of them.

**Comment by vsch** [comment] 2019-01-27 08:57
Please see #533 and #642 for a solution to this issue.

**Closed** 2019-02-03 22:43 UTC
Labels: bug, fix available, fixed for next release, workaround available
