### ISSUE TITLE
Exception on Startup after last Update

### ISSUE THREAD

**Issue by ulise** [vsch/idea-multimarkdown#87] opened 2015-12-21 12:20 UTC
After the Update 21.12.2015:
Plugin disabled when IntelliJ restarts.
Cheers,
Uli

Plugin 'com.vladsch.idea.multimarkdown' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.ExceptionInInitializerError
    at com.vladsch.idea.multimarkdown.settings.MarkdownCssSettings$Companion$DEFAULT$2.invoke(MarkdownCssSettings.kt:177)
    at com.vladsch.idea.multimarkdown.settings.MarkdownCssSettings$Companion$DEFAULT$2.invoke(MarkdownCssSettings.kt:176)
    at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:125)
    at kotlin.LazyKt.getValue(Lazy.kt:77)
    at com.vladsch.idea.multimarkdown.settings.MarkdownCssSettings$Companion.getDEFAULT(MarkdownCssSettings.kt)
    at com.vladsch.idea.multimarkdown.settings.MarkdownApplicationSettings$SharedState.<init>(MarkdownApplicationSettings.kt:261)
    at com.vladsch.idea.multimarkdown.settings.MarkdownApplicationSettings.<init>(MarkdownApplicationSettings.kt:49)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
    at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:220)
    at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
    at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
    at com.intellij.util.pico.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:59)
    at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:232)
    at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
    at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:212)
    at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:46)
    at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:37)
    at com.vladsch.idea.multimarkdown.settings.MarkdownApplicationSettings$Companion.getInstance(MarkdownApplicationSettings.kt:329)
    at com.vladsch.idea.multimarkdown.MultiMarkdownPlugin.<init>(MultiMarkdownPlugin.kt:127)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
    at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:220)
    at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
    at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
    at com.intellij.util.pico.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:59)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:495)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:123)
    at com.intellij.openapi.application.impl.ApplicationImpl.access$801(ApplicationImpl.java:90)
    at com.intellij.openapi.application.impl.ApplicationImpl$12.run(ApplicationImpl.java:496)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:505)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:107)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:454)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:446)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:194)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:52)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:361)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.io.FileNotFoundException: nullmultimarkdown_darcula.css (Zugriff verweigert)
    at java.io.FileOutputStream.open0(Native Method)
    at java.io.FileOutputStream.open(FileOutputStream.java:270)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
    at java.io.FileWriter.<init>(FileWriter.java:90)
    at com.vladsch.idea.multimarkdown.MultiMarkdownPlugin.updateTempCssWithCustomFontCopy(MultiMarkdownPlugin.kt:241)
    at com.vladsch.idea.multimarkdown.MultiMarkdownPlugin.createTempCssWithCustomFont(MultiMarkdownPlugin.kt:235)
    at com.vladsch.idea.multimarkdown.MultiMarkdownPlugin.createTempCssWithCustomFontExtURL(MultiMarkdownPlugin.kt:222)
    at com.vladsch.idea.multimarkdown.MultiMarkdownPlugin.resourceFileURL(MultiMarkdownPlugin.kt:75)
    at com.vladsch.idea.multimarkdown.editor.util.HtmlResource$Companion.resourceFileUrl(HtmlResource.kt:48)
    at com.vladsch.idea.multimarkdown.editor.util.HtmlCssResource.<init>(HtmlCssResource.kt:30)
    at com.vladsch.idea.multimarkdown.editor.resources.SwingHtmlCssProvider.<init>(SwingHtmlCssProvider.kt:35)
    at com.vladsch.idea.multimarkdown.editor.resources.SwingHtmlCssProvider.<clinit>(SwingHtmlCssProvider.kt:29)
    ... 62 more

**Comment by vsch** [comment] 2015-12-21 17:58
Thank you for the report, @ulise. I am looking into it now.

**Comment by Ferocit** [comment] 2015-12-21 23:46
Same problem here, to give some translation:

Caused by: java.io.FileNotFoundException: nullmultimarkdown_darcula.css (Zugriff verweigert)

"Zugriff verweigert" = "Access denied"

**Comment by vsch** [comment] 2015-12-22 00:20
@Ferocit thank you for the clarification. in that case it already has a fix from #92, 

@ulise, @Ferocit 
Here is the fixed version: https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.3.0.1.zip please download and install plugin from disk.

**Comment by ulise** [comment] 2015-12-22 07:26
@vsch : Sorry, got anoter exception after installing the new one from disk.
(Removed the last one by uninstall)
Here is the Output.
Plugin 'com.vladsch.idea.multimarkdown' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.NoClassDefFoundError: javax/json/JsonException
    at com.vladsch.idea.multimarkdown.MultiMarkdownPlugin.<init>(MultiMarkdownPlugin.kt:111)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
    at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:220)
    at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
    at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
    at com.intellij.util.pico.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:59)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:495)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:123)
    at com.intellij.openapi.application.impl.ApplicationImpl.access$801(ApplicationImpl.java:90)
    at com.intellij.openapi.application.impl.ApplicationImpl$12.run(ApplicationImpl.java:496)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:505)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:107)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:454)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:446)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:194)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:52)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:361)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: javax.json.JsonException PluginClassLoader[com.vladsch.idea.multimarkdown, 1.3.0]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 40 more

**Comment by axelcostaspena** [comment] 2015-12-22 08:40
For me it was fixed with 1.3.0.1

**Comment by vsch** [comment] 2015-12-22 11:19
@ulise, the exception is caused by not finding a class that is in one of the jars included in the plugin distribution zip, javax.json-1.0.4.jar. I compared the zip file in this repository to the original file in my dev directory and they are identical and the JsonException class is there.

Can you download the file again and install. There is no need to uninstall the previous version. Installation replaces the directory contents with the contents of the zip file. While you are re-installing might as well get another bug fix in by installing the fix that resolves absolute link address resolution fix: <https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.3.0.1.zip>

If the error persists, I will have to think of what else could cause a class in a distribution jar not to be found in your system.

**Comment by Ferocit** [comment] 2015-12-22 11:51
1.3.0.1 is working for me.

**Comment by ulise** [comment] 2015-12-23 13:55
Even after getting and copying the zip again, nothing changed. I´m not a intellij developer, but could it be a classloader issue? I have no idea how to trace this.

**Comment by vsch** [comment] 2015-12-23 14:05
@ulise, it could be an issue with the library. If that class has dependencies and they are missing or incompatible the same error would result. Let me look into what those classes require.

With JetBrains offering so many great products on all major OS varieties and versions, makes it that much harder to diagnose the issue.

In the meantime can you let me know your OS, the boot JDK for the IDE and what JetBrains product are you using. All these are big factors. 

The boot JDK you can see in the about box, labeled **JRE**, or just the OS and a screenshot of the about box will do.

<img width="640" alt="screen shot 2015-12-23 at 9 02 24 am" src="https://cloud.githubusercontent.com/assets/10299086/11977784/eb8a2418-a953-11e5-9cd7-5f26f1d1046f.png">

**Comment by ulise** [comment] 2015-12-23 17:04
Hi, 
it´s IntelliJ 
IC143.1184 Community
VM: 1.8.0_51-b16 x86 (64)

Running on Windows 10
Multimarkdown was the first plugin, I installed.
Cheers,
Uli

![unbenannt](https://cloud.githubusercontent.com/assets/3177557/11981051/89252506-a99f-11e5-8ff5-d0e3f4ae6613.jpg)

**Comment by vsch** [comment] 2015-12-23 17:06
@ulise thanks for the specifics. I have Windows 10 and I will install IDEA 15 on it and try to duplicate the bug. It will go a long way to help me figure out what is going wrong.

**Comment by vsch** [comment] 2015-12-24 15:38
@ulise, I got the Windows environment up and running but could not duplicate the exception with 1.3.0.2 fixed version. Although, the original 1.3.0 release did have an exception. I will make another build with a few more fixes and Kotlin runtime update to latest version and post a link so you can try it.

If the problem persists with the new build, then I'll have to think of other things to try in order to isolate the source of the error.

**Comment by vsch** [comment] 2015-12-24 21:53
@ulise, I made as many fixes as I could think of and tried this version on my Windows 10, IDEA 15 CE.
Please let me know how it performs on your system. Happy Holidays.

Latest interim release with fixes for exceptions and some feature additions <https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.3.0.9.zip>

**Comment by ulise** [comment] 2015-12-27 16:45
@vsch 1.3.0.9 runs for me. Many thanks. I really like the plugin.

**Comment by vsch** [comment] 2015-12-27 16:50
@ulise thank you for the update. I now have Windows 10 testing as part of my release sanity test. ;)

**Closed** 2016-01-04 19:45 UTC
Labels: duplicate, fix available, fixed for next release, ☹ bug
