### ISSUE TITLE
Better code color consistency needed

### ISSUE THREAD

**Issue by holgerbrandl** [vsch/idea-multimarkdown#400] opened 2017-03-01 10:12 UTC
By default (I think at least), inlined code is red but chunk code is gray.

They should have the same color imho. Also showing inlined code bits in red, looks like an error which it is not.
![image](https://cloud.githubusercontent.com/assets/200952/23454728/76973f7c-fe6d-11e6-8330-4cbd7d29732c.png)

I know that I can change it under Editor->Color&Fonts, but having sensible defaults is imho better.

In general red should be avoided in healthy code bits because most languages use red to indicate errors. E.g. in java there is no red at all when using the default color scheme. In contrast the MN plugin is using red for unordered lists `*` inlined code and backticks.

**Comment by vsch** [comment] 2017-03-01 15:09
@holgerbrandl, I will change the defaults. I chose this color scheme to make inline code more visible so I can see where it is missing. You are right and I will customize my own scheme to do this.

**Comment by vsch** [comment] 2017-03-01 19:45
Also changed copy Markdown as HTML formatted text and PDF export to align inline code color with indented and fenced code.

BTW, I found the bug #402 in PDF export which expects a selection of text to export, if there is no selection it does nothing instead of exporting the document. This too will be fixed in the next EAP plugin release. A workaround is to select all before exporting PDF.

**Comment by vsch** [comment] 2017-03-01 20:27
EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.

**Comment by holgerbrandl** [comment] 2017-03-02 09:10
Cool, pdf export works for me as well now.

Code chunks are much more consistent now.

* backticks still use inconsistent colors 
* lists asterisks are still red and look like errors to me (because red==error in intellij)

![image](https://cloud.githubusercontent.com/assets/200952/23500455/651a5784-ff30-11e6-986f-be08c62154d8.png)

**Closed** 2017-03-27 11:57 UTC
Labels: enhancement, fix available, fixed for next release
