### ISSUE TITLE
Editor wrap not functioning

### ISSUE THREAD

**Issue by yunti** [vsch/idea-multimarkdown#455] opened 2017-06-08 17:58 UTC
I have soft wraps disabled under settings->general ->"use soft wraps in editor'

However trying to enable this in the markdown editor (not preview) seems not to work. 

My settings are:
Code style-> Markdown->
Wrap on typing: Wrap
Disabled if soft wraps - ticked

Then under Text
Wrap Text - ticked

Also unders Languages and Frameworks->

Soft wrap: Default
Soft wrap at right margin - ticked.

That seems like a lot of settings to wrap text.  Not sure what the differences are.
The intent is to only soft wrap Markdown files in the editor and not the preview (all other file type for soft wrap to be left as normal)

**Comment by vsch** [comment] 2017-06-08 19:02
@yunti, when Markdown "Soft Wrap" is set to "Default", markdown documents will follow the Settings > General > "use soft wraps in editor"

To enable them in markdown separately from general settings select "Enabled", to disable "Disabled"

You might also want to set code style under "Text", "When soft wrap is enabled" to "Disable Formatting" to not wrap on format or to "Infinite right margin" to "unwrap" paragraphs to a single line. The latter is useful if you want to convert markdown to processor which uses "Hard Wraps", like GitHub comments by turning on soft wraps and formatting the document before copy/paste.

**Comment by yunti** [comment] 2017-06-09 13:36
thanks.

Currently some things do wrap but not eg the image links:

<img width="1016" alt="screen shot 2017-06-09 at 14 35 15" src="https://user-images.githubusercontent.com/1826271/26977763-ef036e7a-4d20-11e7-8dde-3ea4b173b686.png">
<img width="698" alt="screen shot 2017-06-09 at 14 35 03" src="https://user-images.githubusercontent.com/1826271/26977766-f06fc0c4-4d20-11e7-9bd3-6f4b3b064232.png">
<img width="661" alt="screen shot 2017-06-09 at 14 30 53" src="https://user-images.githubusercontent.com/1826271/26977768-f1be29d4-4d20-11e7-9294-441f0fce100d.png">
<img width="391" alt="screen shot 2017-06-09 at 14 30 42" src="https://user-images.githubusercontent.com/1826271/26977771-f37f8f42-4d20-11e7-8aec-3134078e7944.png">

**Comment by vsch** [comment] 2017-06-10 17:22
@yunti, links and image links are not wrapped by design because there is no general way to wrap them without changing the result.

If you want to remove the distraction of long links from your text, you should convert them to reference links (using the intention) and configure the code style to put them at the bottom of the document where they will be out of the way.

**Comment by yunti** [comment] 2017-06-12 13:20
thanks, good tip about reference links.

Note that the editor default softwraps does seem to wrap long link addresses, (but not if markdown navigator plugin is disabled)

<img width="815" alt="screen shot 2017-06-12 at 14 19 11" src="https://user-images.githubusercontent.com/1826271/27035707-3af4493e-4f7a-11e7-942c-a50f339bb5b2.png">

**Comment by vsch** [comment] 2017-06-21 11:22
@yunti, this will happen when you don't have the closing `)` of the link while typing. The reason is that the parser does not recognize the text as a link.

You can use the link shortcut or the template to insert a full link before filling in the URL or to have the closing `)` before typing the URL.

**Closed** 2019-03-09 21:24 UTC
Labels: question
