### ISSUE TITLE
IntelliJ IDEA 2016.3 EAP :  java.lang.NoClassDefFoundError: com/intellij/profile/Profile

### ISSUE THREAD

**Issue by bstout** [vsch/idea-multimarkdown#327] opened 2016-11-02 17:29 UTC
Updating to latest Intellij, on startup throws error:

IntelliJ IDEA 2016.3 EAP
Build #IU-163.7342.3, built on November 1, 2016
IntelliJ IDEA EAP User
Expiration date: December 1, 2016
JRE: 1.8.0_112-release-408-b2 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

```java
Plugin 'com.vladsch.idea.multimarkdown' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.NoClassDefFoundError: com/intellij/profile/Profile
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:274)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:270)
    at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:239)
    at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:119)
    at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:73)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:62)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at com.vladsch.idea.multimarkdown.settings.MarkdownApplicationSettings$SharedState.<init>(MarkdownApplicationSettings.kt:278)
    at com.vladsch.idea.multimarkdown.settings.MarkdownApplicationSettings.<init>(MarkdownApplicationSettings.kt:44)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
    at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:220)
    at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
    at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
    at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:58)
    at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:228)
    at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:238)
    at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:205)
    at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:49)
    at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:39)
    at com.vladsch.idea.multimarkdown.settings.MarkdownApplicationSettings$Companion.getInstance(MarkdownApplicationSettings.kt:354)
    at com.vladsch.idea.multimarkdown.MultiMarkdownPlugin.initComponent(MultiMarkdownPlugin.kt:109)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:501)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:125)
    at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:441)
    at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:448)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:109)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:400)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:386)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:74)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.intellij.profile.Profile PluginClassLoader[com.vladsch.idea.multimarkdown, 2.1.1.20]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:64)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 61 more
```

**Comment by vsch** [comment] 2016-11-02 17:43
@bstout, thank you for the heads up. I upgraded to latest EAP now and will debug the issue.

**Comment by vsch** [comment] 2016-11-02 18:08
@bstout, seems that the previous issue with class not found from issue #315 is back in the latest release.

I commented on previously closed YouTrack issue: https://youtrack.jetbrains.com/issue/IDEA-162576 that the issue is back with another class in the latest release.

**Comment by vsch** [comment] 2016-11-02 19:20
This is caused by an API change in the IDE. I will make an update as soon as I have it working.

**Comment by vsch** [comment] 2016-11-02 23:01
@bstout, plugin's EAP update channel has new release 2.1.1.22 with a fix for this issue.

**Comment by vsch** [comment] 2016-11-22 17:24
Found another cause for this. A jar was included in the distribution that is only needed for compilation. It is part of the IDE distribution.

The next EAP release, coming today will fix this.

**Comment by vsch** [comment] 2016-11-23 09:45
EAP update released. Has lots of new features and improvements. You can enable the EAP update channel in the plugin or download and install from disk: https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.2.1.1.40.zip

**Closed** 2016-12-01 12:52 UTC
Labels: bug, fix available, fixed for next release
