### ISSUE TITLE
Copy as reference copies invalid link

### ISSUE THREAD

**Issue by holgerbrandl** [vsch/idea-multimarkdown#768] opened 2019-08-27 10:27 UTC
When using the copy reference action from the context menu an incorrect reference including the line number is copied
 ![image](https://user-images.githubusercontent.com/200952/63763796-be665200-c8c5-11e9-82e7-8ab40d3c36c2.png)

This reference can not be resolved when being used as link target

![image](https://user-images.githubusercontent.com/200952/63763812-c6be8d00-c8c5-11e9-8043-26588996ec35.png)

The copy reference action should rather copy the anchor link (in this case `elastic_monitor/README.md#how-to-rebuild-the-r-report`) where applicable.

**Comment by vsch** [comment] 2019-08-28 21:18
@holgerbrandl, the reference copy is provided by the IDE which copies the file name and line number.

I will need to add either an Md reference copy or see if there is an extension to override the IDE one for Markdown.

The override should copy a link to the header so that paste into markdown will adjust the link like it would if you manually created a link in the file `[How to rebuild the R report](#how-to-rebuild-the-r-report)`, copied it, then pasted it in another file (or even another IDE). 

I think this is great idea and will make creating specific links to headings easier than using completion.

**Comment by holgerbrandl** [comment] 2019-08-28 21:43
Glad that you like the idea. 

In fact the reference copy does not always copy the name and the line number. E.g. in kotlin it copies the package and the element name. E:g.
![image](https://user-images.githubusercontent.com/200952/63894704-9bcf5880-c9ed-11e9-8b72-d615346ac086.png)


becomes `krangl.DuplicateNameResolver.resolve` (which relies on the parse-tree of the file). Fingers crossed that they expose this as custom language API.

**Comment by vsch** [comment] 2019-08-29 14:12
@holgerbrandl, the fix was easier than anticipated. All I had to do was implement a **`QualifiedNameProvider`** since I already handle fqn string resolution on paste it was a matter of adding a condition for fqn resolving to markdown anchor ref target element and pasting a link to it.

Works across IDE instances and projects. Copy reference in one instance or project and paste in another to get a link.

Handles:
* Headings (with or without explicit id attribute)
* HTML `a` tags with `id` or `name` attribute
* Attributes element with `id` attribute

EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)

**Comment by holgerbrandl** [comment] 2019-09-02 06:14
Thanks @vsch, I've tried the EAP build and it copies the title tag correctly. The only regression (at least I think it was working differently before, is that it is now always pasting the complete path and not a relative link (within the same file or in files in the same directory:

```
file:/D:\documents\arbeitsmappe\big_data\spark\spark.md#reading-log
```
Before it was (if I remember correctly just (the more correct imho)
```
./spark.md#34
```

**Comment by vsch** [comment] 2019-09-02 11:45
@holgerbrandl, I did not check it under Windows. It seems I forgot to account for the path separator. I will check this because on OS X it does paste a relative URL but the presense of `\` in the path looks wrong for URLs. They should be in a system independent format and always use `/`.

**Comment by vsch** [comment] 2019-09-11 00:08
@holgerbrandl, it was the IDE virtual file from URL issue. The library always expects `file:///` prefix while on Windows it is `file:/C:...` so code needs to adjust file URI prefix.

EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)

**Closed** 2019-12-19 22:37 UTC
Labels: bug, fix available, fixed for next release
