### ISSUE TITLE
Indents with 4 spaces instead of 2 as I like

### ISSUE THREAD

**Issue by vjpr** [vsch/idea-multimarkdown#466] opened 2017-07-19 18:56 UTC
I can't find an option to manually set the spaces.

**Comment by vsch** [comment] 2017-07-20 02:17
@vjpr, in markdown indentation spaces are significant and will be interpreted differently by different processors. So you cannot change indentation without changing the processor used.

The parser syntax is selected in settings (preferences on OS X) under Languages & Frameworks > Markdown > Parser, in Syntax Options, Lists: dropdown. Select CommonMark which will be the closest to 2 space indents (for bullet lists), 3 spaces (for numbered lists 0-9, 4 spaces for 10-99, etc).

The parser choices are: 

* `CommonMark`, this is now the GitHub standard and uses 4 spaces for indented code. List item indentation needs to align with the first line's text column
* `Fixed 4 spaces`, this is Pandoc, Pegdown and a few other processor compatibility mode and uses 4 spaces for indentation of indented code and list item contents.
* `Old GitHub Doc`, this is old pre-CommonMark GitHub parsing mode and indentation is "strange" because it is a mix of fixed 4 spaces and common mark with some variation. This mode is left in to allow converting old docs formatted for pre-CommonMark github so that they can be converted to CommonMark or Fixed 4 spaces syntax.

![Screenshot_Parser_Lists](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/Screenshot_Parser_Lists.png)

**Comment by vjpr** [comment] 2017-07-21 15:35
When I press the tab key with the cursor is at the first column, I get 4 spaces which creates a code block. But I don't want a code block. If I want a code block I will press the `tab` key twice, or I will use add backticks, or I will hit a keyboard shortcut to create me the code block in whatever is the correct way.

Markdown's advantage is that it is plain-text, which lets me move quickly. I can use indents to organise things if I want, and then come back later and turn them into lists so they render correctly.

At present there is no way to use 2 spaces for indentations, which does work fine on github as demonstrated below:

- test
  - test

1. foo
     bar

I strongly feel that the indentation should be a separate setting, or provide an option to configure it for each scenario.

**Comment by vjpr** [comment] 2017-07-21 15:39
I think there is a bug too. Say I want to indent a flat list.

```
- foo
- bar
```

```
- foo
<press-tab-here>- bar
```

Results in:

```
- foo
    - bar
```

Whereas:

```
- foo
- bar (Markdown Navigator "Increase list level" action)
```

```
- foo
  - bar
```

This is an issue not being consistent with how many spaces a tab inserts.

**Comment by vsch** [comment] 2017-07-21 16:53
@vjpr, I think the solution needs to override the tab key in markdown documents to make it context sensitive. That way after a list item marker it can indent the list item and everywhere else to insert spaces according to the setting.

Similarly for back tab. It should un-indent the list item and everywhere else to back tab.

BTW, the indent list action will indent according to the selected parser. If fixed 4 spaces is the parser mode, indent action will indent by 4 spaces. For the other modes it will indent the item to the next list level, which depends on the previous list item type.

    1. item
    2. item 2 <increase level action>

to get:

    1. item
       2. item 2

Once I implement the tab/shift+tab overrides, I can add a setting for number of spaces for tabs.

**Comment by vjpr** [comment] 2017-07-21 16:57
@vsch What you just said sounds perfect! Looking forward to testing it out.

**Comment by vjpr** [comment] 2017-10-14 18:02
@vsch Any progress on this?

**Comment by vsch** [comment] 2017-10-18 17:46
@vjpr, this affects all the formatting code including wrap on typing.

This part of the code is very brittle because it depends on the IDE implementation and when it updates the PSI tree for the file.

I have not made any progress since I realized that I first have to rewrite that part of the code to make it independent of the IDE implementation details, which change often.

I added it to the to do list and will be addressing it as part of the rewrite of the formatting code.

**Comment by vjpr** [comment] 2017-10-27 10:00
@vsch What's the time frame for the rewrite being done? Is there a branch to see the progress, help out?

**Comment by vsch** [comment] 2017-10-27 23:46
@vjpr, it will be after the next release. I don't want to make such big changes without a long EAP cycle.

I have delayed the next release, waiting for JB to release the 2017.3 version of the IDEs. These are now in public preview so the next release should happen soon after this version of the IDEs is released. Afterwards, I can start on the rewrite of the auto-formating code and consistent handling of tabs.

The code for formatting and wrapping as you type is only in the licensed version and I have not released it into open source. So it is difficult to enlist help on this code.

Additionally, the open source repository has not been updated to the latest versions since the version I am using for the plugin diverged too much and a simple merge is impossible. I have to spend about a week creating a new version and then check it all in.

I have not devoted time to this since there were zero contributions to the open source repository in the year that I kept the two versions in sync. I figured if no one cares enough to contribute, why bother spending time on it.

It is a delicate balance of spending time on the plugin vs having to earn a living. Unfortunately, the plugin sales are not enough to allow me to work on it full time, like I did in the first two and a half years of its development so I have to prioritize support, bug fixes, minor feature improvements and major rewrites based on what else is competing for my time.

It is unfortunate, while Information may want to be free, developers need to eat, pay rent and provide for their families. ;)

**Comment by vjpr** [comment] 2017-10-27 23:58
Understand, really appreciate your work on it!

I think its a really important plugin and the refactoring is killer for people maintaining lots of documentation.

Seems like a very tiny thing to have an option to change 4 spaces to 2 spaces...but I guess I can wait.

**Comment by vsch** [comment] 2017-10-28 00:33
@vjpr, I will try just the 2 space option only. Since it does not make a difference for the code I will add it in without making changes to anything else. It will only affect those that make the change, so it is safe enough since by default no one will be affected.

The bigger change is to have full implementation of all the IDE tab/space options which extends to having embedded tabs with variable number of spaces these tabs represent. 

I don't think I will be able to implement the latter since Markdown and CommonMark treat tabs as having 4 column tab stops in their specs. It is the full options that require the rewrite. Just changing number of spaces inserted when you hit tab does not.

Thank you for the appreciation. I agree with you on having the ability to refactor Markdown. I cannot work with Markdown without the refactoring, formatting, auto-completions, navigation, drag/drop image and link creation.

If you look on the plugin page https://plugins.jetbrains.com/plugin/7896-markdown-navigator you will see a few one star ratings because the free version does not give them a lot of features, eventhough it gives more, looks better and works faster than the permanently free Markdown Support from JetBrains.

Since, my ROI on time spent on this plugin is somewhere in the range of $1 to $2.50 per hour spent during the first two years of full-time development. If anyone wants this job or think they can do it better, they are welcome to it. ;)

**Comment by vsch** [comment] 2017-10-28 14:36
@vjpr, EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.

**Comment by vsch** [comment] 2017-10-28 14:36
@vjpr, in code style > markdown change the indent size to 2. https://github.com/vsch/idea-multimarkdown/wiki/Document-Format-Options#general-options

**Comment by vjpr** [comment] 2017-10-28 15:50
Thank you! Works great.

**Closed** 2017-12-07 17:44 UTC
Labels: enhancement, fix available, fixed :), fixed for next release, question
