### ISSUE TITLE
Collapsible sections - summary/ details don't render details properly.

### ISSUE THREAD

**Issue by yunti** [vsch/idea-multimarkdown#341] opened 2016-11-29 15:17 UTC
Trying to use the collapsible details section as per this thread. https://github.com/dear-github/dear-github/issues/166

Works correctly to give a collapsible section, but the markdown within the details tag fails to render properly (eg italics, bold etc.. fail to render).

eg try with:

`<details><summary>stuff with *mark* **down**</summary><p>
*formatted* **heading** with [a](link)
---
{{stamdard 3-backtick code block omitted from here due to escaping issues}}
Collapsible until here.
</p></details>`

**Comment by vsch** [comment] 2016-11-29 15:34
@yunti did you install the chrome extension or how did you do that. I installed the chrome extension and all seems to show up fine.

<img width="698" alt="screen shot 2016-11-29 at 10 34 34 am" src="https://cloud.githubusercontent.com/assets/10299086/20716203/71e84c3c-b61f-11e6-9990-f41a975aea1a.png">

**Comment by yunti** [comment] 2016-11-29 15:41
Didn't install any chrome extension - not quite sure what you mean - it's just rendering in pycharm /intellij (chrome not needed)?  Will add screenshot to show but plugin broken from other issue

**Comment by vsch** [comment] 2016-11-29 15:47
@yunti, thought you mean in the browser not the preview of the plugin. Did you include the "GitHub Collapse Markdown" script as part of the custom stylesheet or HTML generation?

I will check but I am pretty certain that right now the markdown parser does not parse inlines in code but I will confirm.

**Comment by vsch** [comment] 2016-11-29 15:52
@yunti, seems to work in my version, 

<img width="1481" alt="screen shot 2016-11-29 at 10 49 55 am" src="https://cloud.githubusercontent.com/assets/10299086/20716925/d540d720-b621-11e6-89b5-467ffa1e751d.png">


I added it surrounded by `<script></script>` in the head

<img width="981" alt="screen shot 2016-11-29 at 10 51 20 am" src="https://cloud.githubusercontent.com/assets/10299086/20716913/cbbdefe4-b621-11e6-8ec9-dd6d17bbd7d2.png">
 bottom of the HTML Generation:

where did you include the script?

**Comment by vsch** [comment] 2016-11-29 16:00
@yunti, neat. I'll add the script as a standard Stylesheet script option.

<img width="931" alt="screen shot 2016-11-29 at 10 59 50 am" src="https://cloud.githubusercontent.com/assets/10299086/20717276/030ebe5a-b623-11e6-9590-c9740f99debb.png">
<img width="936" alt="screen shot 2016-11-29 at 11 00 31 am" src="https://cloud.githubusercontent.com/assets/10299086/20717303/126f73c6-b623-11e6-9c45-146836f7b2a5.png">

**Comment by yunti** [comment] 2016-11-29 16:11
I didn't realise it needed a script to be honest, thought it was built in to html 5 http://caniuse.com/#search=details
(presumably the script is probably needed to parse markdown through the tags)   - 

Thanks that would be great if you could add it as standard - hmmm I can't seem to find the relevant script (was it in the link I posted)?.

**Comment by vsch** [comment] 2016-11-29 16:13
@yunti, I will add it to the next EAP and the release. The script you need is here: https://github.com/Mottie/GitHub-userscripts/blob/master/github-collapse-in-comment.user.js

**Comment by vsch** [comment] 2016-11-29 16:16
@yunti, I will add both the collapse in comments and the collapse markdown, so that headers will be collapsible. Thank you for bringing it to my attention. It is a 5 min effort to add these as standard options and will make it easier to deal with large docs.

I will see how I can persist the collapsed/expanded  state across page refreshes that occur every time you edit the document. I need this so that I can collapse sections I am not working on or ones that have animated GIFs, and have them collapsed as I edit the doc.

**Comment by yunti** [comment] 2016-11-29 16:24
Thanks that is a brilliant feature - I was really hoping to be able to get a collapsable section working. 

If you can persist state somehow that would be ideal. So that reopening a document loads the collapsed and expanded sections as they were when it was last edited.  (If that proves not to be easy - I would default to load all collapsed).

It is possible to add a shortcut to create a collapsed section - select section then hit keyboard shorcut/icon?

**Comment by vsch** [comment] 2016-11-29 16:35
@yunti, I'll add a live template to the next release for the collapsed section insert of the `GitHub-collapse-in-comments.js` script. I can see myself using it all the time to collapse the bitmap images I include to make the explanation easier.

As for preserving the state I don't see a problem. It is only a matter of modifying the script so that it gets the collapse information from a variable I will inject into the source and when the collapse state is changed, it saves the new state with a call back to my WebView integration code.

I'll try to fit the persistence into this release but don't think it will make it. Too much risk of not working right and breaking the release. But the next EAP version will have it.

**Comment by yunti** [comment] 2016-11-29 16:40
That sounds brilliant thank you.

**Comment by vsch** [comment] 2016-11-30 05:50
@yunti, new EAP out. In the main settings for the plugin select EAP update channel and check for updates. In the end support for `<details>` requires no script but header collapsing does.

I added a script in the Stylesheet config `Details tag opener` selecting it will always have the details tags open so you can edit them. Otherwise they will always be closed unless you add `open` attribute to the tag as in `<details open>`

There is a `.collapse` live template but you have to enable it. Did not want to have people complain that it gets in the way.

Headers are in the `GitHub Collapse Markdown` but no storage yet of the state so they always default to open. I had to modify the script to get it to work but had no time for the other mods. I'll do them for the release after next. I labeled this feature as experimental.

Enjoy!

**Comment by yunti** [comment] 2016-12-01 20:55
Thanks just saw the update automatically appear today (2.2.0). However although it worked previously before the update the rendering of markdown inside the tags no longer works for some reason. 
I unticked the old script in HTML Generation -> Head bottom and ticked: Style sheets-> Scripts: github collapse markdown.  (also ticked details tag opener - as not sure if this was related).  
Unfortunately parsing of markdown within details tag isn't working.

Let me know if I can send you some log details etc...

**Comment by vsch** [comment] 2016-12-01 21:05
@yunti, post the markdown in fenced code markers so I can take a look at it. For `<details>` tag you don't need a script. The browsers handle it. The characters before the tag are only needed to prevent the markdown parser from parsing it as an HTML block, in which case it will not parse the markdown inside.

Instead of a back tick I use `&nbsp;` it does the job without leaving visual trash once rendered. The markdown parsers will wrap the opening and closing tags in `<p></p>` but the browser gets through the unbalanced tags. It is a hack to get something that really should be part of markdown but is not.

The GitHub Collapse Markdown is a script for collapsing headers. Will be really nice when I implement persistence for the state of each header. Until then it is more of a gimmick than a useful feature.

The `Details tag opener` is a script which ensures that all detail tags are open after preview is refreshed. It is useful for seeing the content while editing. You don't need this script if you don't want your `<details>` tags open on refresh.

**Comment by yunti** [comment] 2016-12-02 12:01
the code is:
<img width="461" alt="screen shot 2016-12-02 at 11 57 17" src="https://cloud.githubusercontent.com/assets/1826271/20833228/838964e4-b886-11e6-8602-02b1b3a668f0.png">

but actually it doesn't matter as it seems to be working based on the actual markdown headings (ie without need to include `<details>` tags, which is much better - and actually ideal. With different colours for different heading levels.   That's just what I needed.   
<img width="887" alt="screen shot 2016-12-02 at 11 59 09" src="https://cloud.githubusercontent.com/assets/1826271/20833290/d884f97c-b886-11e6-8b7e-8bbb32607c62.png">


Persistence will be a great addition, but for now this is way better than a gimmick (particularly as I can start with all collapsed).  Thanks.

**Comment by vsch** [comment] 2016-12-02 12:41
@yunti, the reason the first details tags are not working is you do not have something in front of the tag so that the markdown parser interprets it as an HTML Block, in which case no markdown parsing is done on the content. If you add `&nbsp;` in front of it then it will work because the parser treats it as inline HTML and parses markdown in the content.

As for the headers being collapsible without this script it is the `GitHub Collapse Markdown` script that does this. The intention for the `<details>` tags and this script are different. The details are for adding collapsible sections in your markdown that **will display as collapsible** after markdown is processed by any markdown processor 

The GitHub Collapse Markdown script is there to make heading collapsible in preview but **will not affect the rendering** of the file where ever you finally process it, like GitHub, for example.

So the two serve different functions and you can user either one or both as it suits your need.

**Comment by yunti** [comment] 2016-12-02 12:45
Ah I see.  Thanks.

**Comment by vsch** [comment] 2017-02-15 19:44
@yunti, state persistence added to JavaFX preview and GitHub Collapse Markdown modified to restore collapsed state of headings between file editing updates and file close/open actions.

Headings are not collapsed by default but you can always hold the SHIFT key as you collapse a heading and all sibling headings will also be collapsed.

EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.

**Closed** 2017-02-15 19:45 UTC
Labels: enhancement, fixed :), question

**Comment by yunti** [comment] 2017-02-16 10:27
Brilliant thanks.  I'll try that out in the next few days.

**Comment by QueenBeeSC** [comment] 2017-04-18 05:47
How do I create collapsible headers with <details> ? When I try to add the hashtags inside <details> <summary>##New User</summary> it doesn't translate as a header anymore. Also the content inside the collapsible section isn't reading as markdown with the GitHub pages as it does in the preview? I am very new to markdown and I am learning as I go, any help will be much appreciated.

**Comment by vsch** [comment] 2017-04-18 17:13
@QueenBeeSC, GitHub syntax for headings requires a space between the last `#` and the heading text and it must be on a line by itself.

As for not processing Markdown in block HTML, it is a limitation of GitHub. One way to get around it is to force the `<details>` tag to be processed as inline HTML by prefixing it with some text, at least `&nbsp` so that the block is parsed as a paragraph instead of an HTML block. You also need to make sure the HTML open/close tags are balanced.

```html
&nbsp;<details><summary>Collapsed Text</summary>When I try to add the hashtags inside
&nbsp;<details><summary>Hidden Heading</summary>
## New User
&nbsp;</details></details>
```

Will give you:

&nbsp;<details><summary>Collapsed Text</summary>When I try to add the hashtags inside
&nbsp;<details><summary>Hidden Heading</summary>
## New User
&nbsp;</details></details>

**Comment by TheBoxyBear** [comment] 2021-07-18 16:54
I'm looking to replicate what OP did by making the header itself collapsible. Tried getting the raw text by generating a quote reply but it doesn't seem to work. Could @yunti please provide the content of your original comment in a code block?
