### ISSUE TITLE
tables stopped rendering

### ISSUE THREAD

**Issue by jimlongo56** [vsch/idea-multimarkdown#287] opened 2016-08-15 15:02 UTC
My tables have stopped appearing in HTML view mode.
V 2.0.0 with PHPStorm

*Markdown View*

	**MYSQL Passwords**

	platform | password
	--- | ---
	production	| redacted~IE2v
	staging     | redacted50v
	dev	        | redactedaIF
	sandbox	    | redactedoaIF
	legacy	    | redacted

*HTML Preview*
![screen shot 2016-08-15 at 10 59 06 am](https://cloud.githubusercontent.com/assets/6787988/17668498/7c84e768-62d7-11e6-93a9-a72efcb9b7f5.png)

**Comment by vsch** [comment] 2016-08-16 00:55
@jimlongo56, it's a bug. I will release a patch shortly that fixes this issue. The code is not checking for lack of pipe separator after the last table cell and causes a NPE.

**Comment by vsch** [comment] 2016-08-16 01:03
@jimlongo56, patch release available from EAP channel or direct download: <https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.2.0.0.2.zip>

**Comment by jimlongo56** [comment] 2016-08-16 17:43
@vsch thanks for that, but I downloaded and installed this zip file and I still have the issue that tables don't render

**Comment by vsch** [comment] 2016-08-16 17:49
@jimlongo56, is it all tables that are not rendering or just some?

Under Languages & Frameworks > Markdown > Parser there is an option for Tables. Is it selected?

There is also a new GitHub Table Rendering setting that will render tables according to GitHub markdown rules which are more limiting than the plugin parser. That way the source will recognize tables that will render as text so that you can use plugin table action to make corrections.

![screenshot_parser_tables](https://cloud.githubusercontent.com/assets/10299086/17709679/266da23e-63b8-11e6-972c-4ebf68c7f3db.png)

**Comment by jimlongo56** [comment] 2016-08-16 17:53
Yes all tables seem to be affected.
Yes the "Tables" option is checked in Markdown>Parser
![screen shot 2016-08-16 at 1 53 08 pm](https://cloud.githubusercontent.com/assets/6787988/17709858/cb39d26a-63b8-11e6-89d1-224f50516ca3.png)

**Comment by vsch** [comment] 2016-08-17 00:48
@jimlongo56, can try turning off the "Table Rendering" option in "GitHub Syntax".

If the tables start to render with this option off then your tables do not conform to GFM table syntax limitations: header columns == separator columns, one header row, etc.

Otherwise, can you post a sample table because the previous sample renders on the patched version.

**Comment by jimlongo56** [comment] 2016-08-17 02:10
@vsch Thanks, I tried your suggestion, no change.

It's odd because it worked before, although every once in a while I'd have to restart PHPStorm to get tables to render again.

Tables are standard GFM tables, I don't use the optional outer pipes, but I tried adding them and it doesn't matter.

This is on 2 different installations of PHPStorm. My Mac mini and and an Air.

**Comment by zhxiaogg** [comment] 2016-08-17 10:00
@vsch I have the same problem using V 2.0.0 and IntelliJ IDEA 2016.2.1

**Comment by skidank** [comment] 2016-08-23 23:08
I have the same problem. No table renders regardless of settings. I've tried the patched version, no help. Even this simple table does not render (I've tried other syntax variants too):

```
| Column | Column | Column |
| ------ | ------ | ------ |
| value  | value  | value  |
```

**Comment by 3ndriu** [comment] 2016-08-24 12:42
This fix (v2.0.0.2) does not work for me either. I've tried to check and uncheck 'Table rendering' but neither of those settings worked. I've also tried using different syntaxes (like @jimlongo56 and @skidank ones).

I'm using basic version on IDEA Community Edition 2016.2.2 and Windows 10.

**Comment by vsch** [comment] 2016-08-24 14:16
I am in the process of duplicating the second bug of tables not rendering. I had encountered this bug once after the IDE was up for over a week. Unfortunately it was my main IDE and not in a debug session. Restarting the IDEA corrected the bug.

I am now running a debug version. I am sure that eventually this will cause the bug to appear which is needed to find out why table rendering stops after the IDE stays up for considerable amount of time.

**Comment by skidank** [comment] 2016-08-24 14:25
Uptime has no impact on the issue for me. The bug appears on restart and persists across any number of restarts.

**Comment by jimlongo56** [comment] 2016-08-24 14:50
Same here, I've restarted multiple times to see if it makes any difference. It doesn't.

**Comment by vsch** [comment] 2016-08-24 18:49
@jimlongo56, @skidank can you please send me the plugin shared settings file that stores the plugin config. I want to make sure that it is not a bug that has some cross dependency for tables with another setting that causes the table option to be disabled even when it shows as selected in parser settings.

The file is `markdown_navigator.shared.xml` in the `options` subdirectory in IDE preferences.

**Comment by skidank** [comment] 2016-08-24 20:55
Here's mine.

[markdown_navigator.shared.xml.zip](https://github.com/vsch/idea-multimarkdown/files/435661/markdown_navigator.shared.xml.zip)

**Comment by jimlongo56** [comment] 2016-08-24 22:19
[markdown_nav.zip](https://github.com/vsch/idea-multimarkdown/files/435783/markdown_nav.zip)

**Comment by vsch** [comment] 2016-08-25 17:26
@jimlongo56, @skidank, thank you for the config files. In version 2.0 the component name for the shared settings was changed from "ApplicationShared" to "Markdown Navigator" to make the settings options show an identifying text.

However, the files you have still have "ApplicationShared" as the component name. Replacing my files with yours resulted in the component name being renamed. I have no idea why your files still have the old component name. The code doing this renaming first loads the old component name and if it has some settings uses this for the settings, if the old set is empty it will load the new component name. However, when saving only the new component name is saved and the old one reports an empty options set. This results in settings being saved under the new component the first time the plugin starts up.

Is there something that would cause the file not to be saved on IDE exit, which would explain why the component name is not changed?

Can you edit the `markdown_navigator.shared.xml` and change the second line in the file from:

      <component name="ApplicationShared">

to:

      <component name="Markdown Navigator">

And see if the tables will be rendered.

**Comment by vsch** [comment] 2016-08-25 17:28
@jimlongo56, previous comment does not apply to your settings. I am looking into your case separately since the component name is correct.

**Comment by vsch** [comment] 2016-08-25 17:37
@jimlongo56, @skidank scratch previous theories. I found the bug that would fail to initialize table options under some circumstances.

Thank you very much for your feedback to help me resolve the issue.

I will post a patch release shortly that addresses the bug.

**Comment by vsch** [comment] 2016-08-25 17:54
@jimlongo56, @skidank, @3ndriu, patch release available with a fix for this issue:

<https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.2.0.0.8.zip> 

Please let me know if your issue is resolved.

**Comment by skidank** [comment] 2016-08-25 18:18
That worked for me! Thanks!

**Comment by jimlongo56** [comment] 2016-08-25 21:28
Thanks!

**Comment by 3ndriu** [comment] 2016-08-26 06:45
Works for me as well. Thanks!

**Comment by jimlongo56** [comment] 2016-08-27 15:04
Unfortunately it only half worked for me.

Works on macMini, doesn't work on macbookAir.
Both running the same OS, same version of PHPStorm.  (both are the latest available).

**Comment by vsch** [comment] 2016-09-02 15:40
@jimlongo56, are you sure the config on macbookair has tables enabled and you are not getting any errors?

Is there a difference in the configuration between the two systems?

**Comment by jimlongo56** [comment] 2016-09-02 15:52
Everything's the same afaik.  Same OS, same version of PHPSTorm.
Noticed the Markdown>Parser>Table rendering setting is not selectable in the prefs.
![screen shot 2016-09-02 at 11 50 38 am](https://cloud.githubusercontent.com/assets/6787988/18209857/ab301454-7103-11e6-8077-d82e34aa7e2f.png)
 Only other oddity is that PHPStorm insists on indexing all the files everytime I open it.

Thanks.

**Comment by vsch** [comment] 2016-09-02 15:57
@jimlongo56, the rendering is disabled when tables option is disabled. That would cause the tables not to render:

<img width="1015" alt="screen shot 2016-09-02 at 11 55 27 am" src="https://cloud.githubusercontent.com/assets/10299086/18209971/565b001e-7104-11e6-83b0-e5e7b1ae40cc.png">

<img width="992" alt="screen shot 2016-09-02 at 11 55 40 am" src="https://cloud.githubusercontent.com/assets/10299086/18209974/59b96bba-7104-11e6-9d7d-ed0549f768c1.png">

**Comment by jimlongo56** [comment] 2016-09-02 15:58
Doh!

Thanks again.

**Closed** 2016-09-11 18:24 UTC
Labels: fix available, fixed for next release, ☹ bug
