### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by inf3rno** [vsch/idea-multimarkdown#175] opened 2016-03-17 05:29 UTC
I have about 450MB memory used by editing an md file without this plugin. By using this plugin Webstorm tells me by 900MB that it is out of memory. The md file is not that big, so I can hardly imagine what uses about 500MB memory by displaying a header, some text and an image.

**Comment by vsch** [comment] 2016-03-21 22:35
@inf3rno, to help me isolate the issue can you tell me if you are running the plugin with WebView preview or Swing Preview?

And if it is WebView can you please switch to Swing based preview and see if the problem persists.

I want to narrow down under what conditions the problem shows up.

**Comment by inf3rno** [comment] 2016-03-22 18:55
How can I find out which preview I use?

**Comment by vsch** [comment] 2016-03-22 18:59
In preferences/settings. Lobo evolution is experimental and is not fully supported so only Swing and WebView should be used for normal operation.

<img width="1001" alt="screen shot 2016-03-22 at 2 58 03 pm" src="https://cloud.githubusercontent.com/assets/10299086/13964089/81bf8992-f03e-11e5-8065-7586c85e43f3.png">

**Comment by inf3rno** [comment] 2016-03-22 22:06
It's the JavaFX. Every time I edit the md file and change tab to preview, it appears to increase the used memory with 20-30MB.

**Comment by svenax** [comment] 2016-05-20 13:47
I have similar problems on OSX 10.11 and java 1.8.0_45. After a while the editor becomes unresponsive, each keystroke taking several seconds to process. Finally, IntelliJ usually gives up, displaying a dialog prompting me to increase the memory allocation. This happens both with and without the preview displayed.

**Comment by vsch** [comment] 2016-05-20 14:29
@svenax, JavaFX in pre JRE 1.8.0_51 is less than stable. Ideally for JavaFX needs a later JRE preferably 1.8.0u66 or later. 

The bundled JDK with JetBrains IDE's starting with IDEA 15 and later is very good for JavaFX support. 

If the issue is in JavaFX WebView the only choices are to switch JRE to a later version or to switch to the Swing based preview.

**Comment by svenax** [comment] 2016-05-20 14:46
@vsch OK, I can try upgrading my Java. But in my case I *am* using the default Swing preview. And I also experience problems when the preview is not displayed at all.

**Comment by vsch** [comment] 2016-05-20 14:51
@svenax if you are using the Swing preview then the issue is something else. What is the IDE and version that you are using?

I use both IDEA Ultimate and CE 2016.1 & 2016.2 EAP and PhpStorm 2016.1.2 on OS X 10.10.5 and the memory goes up to about 700MB before dropping to 100MB or 200MB depending on the project.

**Comment by svenax** [comment] 2016-05-20 14:59
@vsch I am using IDEA Ultimate 2016.1. The behavior may is maybe worse when the markdown includes image links. I have not attempted a thorough analysis, I usually just get frustrated when it happens, kill IntelliJ, and edit the markdown files with another editor. But it does occur quite often, not just once in a while.

**Comment by vsch** [comment] 2016-05-20 15:03
@svenax, I will review the code and do some testing of Swing preview with images to see if there is a memory leak in the plugin code.

**Comment by tanndev** [comment] 2016-08-02 22:41
@vsch, I'm experiencing similar problems in IDEA 2016.1.3 on OSX.

I have a 725M max heap that is slowly consumed while editing, even without the preview open. Once the used heap space exceeds ~600M, performance tanks immensely. Closing the document or project does not resolve the problem, restarting IDEA does.

My markdown document has only 319 lines, currently, and no links of any kind. It does, however, contain a relatively large number of headers - down to depth 4 - and inline code blocks.

**Comment by vsch** [comment] 2016-08-03 01:50
@tanndev, I have been trying to duplicate this but have not been able to isolate what could be the cause. I have found that even without the plugin installed the IDE memory use grows slowly with time, with no IDE activity. With the plugin installed it does grow a bit faster but comparing memory dumps has not made anything stand out that is caused directly by the plugin.

There are a lot of IDE internal allocated objects but nothing that I can directly correlate to the plugin. 

The fact that closing the project does not help, means that it is some static allocation. I am reviewing all static members in the classes to see if there is anything other than immutable constants to make sure nothing leaks inadvertently.

**Comment by inf3rno** [comment] 2016-08-03 08:33
I am using Swing since then ~0.5y without any problem.

**Comment by vsch** [comment] 2016-08-05 20:19
@inf3rno, thank you for the update on your case. 

I checked the JavaFX code of the plugin and there are no statics other than constants. However, WebView does have internal caches that are only cleared when the IDE is closed. I have not been able to find how to make WebView flush its cache to release memory. This also includes image cache. 

JavaFX issues are highly platform and version dependent. On OS X there is an open [youtrack issue](https://youtrack.jetbrains.com/issue/RUBY-18230) for older hardware hanging or crashing in JavaFX. Completely outside of Java code control since it happens in a native library.

However, in the case of @tanndev. the preview is disabled so no JavaFX is involved and it is a matter between the IDE and the plugin. I am reviewing all code for all possible leaks. It is slow progress.

**Comment by tanndev** [comment] 2016-08-05 20:23
Unfortunately, I haven't had a chance to work on any Markdown over the last couple days. Next time I get a chance, I'll see if I can get more detailed information.

**Comment by vsch** [comment] 2016-08-05 20:26
@tanndev no problem. I expect this one to be a PITA to isolate.

**Comment by inf3rno** [comment] 2016-08-05 21:02
@vsch  Does this help somehow? http://stackoverflow.com/questions/23668910/how-to-clear-javafx-webview-memory-usage-after-closing-stage

**Comment by vsch** [comment] 2016-11-26 18:19
@inf3rno, @tanndev, @svenax  a new EAP is available on the plugin EAP update channel or direct from this repo: https://github.com/vsch/idea-multimarkdown/blob/master/dist/idea-multimarkdown.2.1.1.42.zip

It may have a fix for the memory issue. I completely rewrote the JavaFX integration. Typing response and preview scrolling speed was fixed too. It was a PITA to find the cause but in the end it was JavaFX issue. I use GitHub style CSS with border around the page, with 3px bottom corner radii. It appears that this was enough for JavaFX WebView to render the contents of that div as a bitmap!!! It would be the last place I would have thought to look. 

The larger the file the bigger the bitmap. I noticed ridiculous pixelation in the PDF if I leave the border on the page when I implemented the print preview but did it did not click right away.

With the CSS fixed I am curious to find out if this also addresses its ridiculous memory footprint.

**Closed** 2017-01-09 03:52 UTC
Labels: fixed :)
