### ISSUE TITLE
Change setext to atx header fails if title starts with <number>.

### ISSUE THREAD

**Issue by holgerbrandl** [vsch/idea-multimarkdown#578] opened 2018-04-06 08:50 UTC
![image](https://user-images.githubusercontent.com/200952/38411843-49de2c82-3988-11e8-8b8c-541c6525f492.png)
The refactoring has no effect. 

I'm using v2.5.2.6

**Comment by vsch** [comment] 2018-04-06 14:02
@holgerbrandl, bug. 

BTW, you have an ordered list item `4.` with a empty text and a child heading `Review and Sync` in it. Not a heading with `4. Review and Sync` text.

GitHub renders it as a list item with a horizontal rule:

```markdown
4. Review and Sync
-----------------
```

4. Review and Sync
-----------------

Adding 3 spaces before the dashes, changes it to list item with heading
```markdown
4. Review and Sync
   -----------------
```

4. Review and Sync
   -----------------

To get just the heading you need to escape the period of the heading `4\.`

```markdown
4\. Review and Sync
-----------------
```

4\. Review and Sync
-----------------

**Comment by holgerbrandl** [comment] 2018-04-06 14:15
And I though markdown would solve all the formatting hassle. :-)

**Comment by vsch** [comment] 2019-01-24 13:42
@holgerbrandl, fixed in next release. The fixes prevent incorrect markdown from being interpreted as heading, was caused by PsiElement replacement without having correct parent prefix.

* Fix: #578, Change setext to atx header fails if title starts with <number>.
  * Fix: equalize setext header marker implementation to properly handle parent indent
  * Fix: toggle header type to properly indent setext header marker based on parent element 
  * Fix: setext header level up/down to properly handle parent indent

**Comment by vsch** [comment] 2019-01-24 19:59
EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)

**Comment by holgerbrandl** [comment] 2019-01-25 08:43
Thanks Vladimir for the fix.

Vladimir Schneider <notifications@github.com> schrieb am Do., 24. Jan.
2019, 20:59:

**Closed** 2019-02-03 22:43 UTC
Labels: bug, fix available, fixed for next release
