### ISSUE TITLE
Documentation for link maps and mapping groups

### ISSUE THREAD

**Issue by jmalin-satori** [vsch/idea-multimarkdown#535] opened 2017-12-08 18:27 UTC
The Markdown Navigator plugin has a option to view or edit link map groups, but there's no documentation for this feature. In addition, I can't find anything related to Markdown that describes link maps.

I'd like to have at least a link to some documentation that discusses the use of this feature.

**Comment by vsch** [comment] 2017-12-08 18:35
@jmalin-satori, I will add a link on the page to the documentation. https://github.com/vsch/idea-multimarkdown/wiki/Modifying-Link-Processing

This is not a "markdown" feature but  a plugin feature to allow custom pre-processing of links so that non-standard links could be resolved by the plugin by transforming the link to what the plugin can resolve.

There is also a reverse transformation so that links in the format that the plugin can resolve are transformed into the text to be used in the link during completions.

**Comment by jmalin-satori** [comment] 2017-12-08 19:04
This is entirely satisfactory. Thank you for your prompt response!

**Comment by vsch** [comment] 2018-01-06 17:59
EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.

**Closed** 2018-03-16 14:36 UTC
Labels: enhancement, fix available, fixed for next release
