### ISSUE TITLE
Network drives links are not resolved correctly

### ISSUE THREAD

**Issue by holgerbrandl** [vsch/idea-multimarkdown#411] opened 2017-03-09 10:55 UTC
Relative link suggestions/resolver results are correct for local files but fail on network drives (ie smb shares on macos sierra.

![image](https://cloud.githubusercontent.com/assets/200952/23747086/b9514d06-04be-11e7-84d1-da27dbe40338.png)

As shown in the project view (and the terminal screenshot to be sure), the `foo.md` is present in the same directory as `bar.md` but not resolvable. 

![image](https://cloud.githubusercontent.com/assets/200952/23747203/21e039e0-04bf-11e7-8bea-f6e0f784e103.png)

What looks a bit suspicious to me is the missing leading `/` in the path suggestion but maybe this is unrelated to the error.

**Comment by vsch** [comment] 2017-03-09 13:10
@holgerbrandl, I will need to setup SMB share to a windows share to see where it fails. Could be assumptions about path format that is not met on a share and causes the matching regex pattern used for filtering files is wrong for a shared drive.

The missing leading / is not a problem because the format you have for completions is `file://` which removes the prefix from completion list display string including the leading / to shorten the display string, don't know why only the file:/// is removed and not the rest of the common path. The same thing happens for local files when you switch to file:// completion mode by invoking completions multiple times.

**Comment by vsch** [comment] 2017-03-09 13:13
@holgerbrandl, are the shared files under a VCS root?

The only files that appears is the file itself which is there for self-reference link completion and not really part of a search match.

**Comment by holgerbrandl** [comment] 2017-03-09 14:56
No, the directory is not under any kind of version control. But the effect
is the same for me when using VCS control on the directory.

Under macos files from mount points should be not distinguishable from
local paths.

Vladimir Schneider <notifications@github.com> schrieb am Do., 9. März 2017,
14:13:

**Comment by vsch** [comment] 2017-03-09 17:19
@holgerbrandl, the plugin uses only the JetBrains Open API for gathering files. The only factor is the regular expression used to filter paths that is constructed but in the case of an empty link the completion is using the project directory prefix which is probably causing the issue for the files to be filtered out.

Is this a module in a project that is located in another directory? If this is the case then the issue is not SMB share but the module handling and I can create a similar project for debugging.

**Comment by vsch** [comment] 2017-03-10 18:22
@holgerbrandl, I think I found the issue. It has to do with trying to complete a link with `http://` addressing format. Since the file you are trying to link to is not under VCS the plugin does not know how to convert it to this addressing mode.

I created a project with a module from another volume. The module is not under VCS. When I use page relative completion I see the file in the completion list. Switching to `http://...` the file no longer appears because the plugin needs to know the remote URL and base directory to create a remote link.

When you invoke completion multiple times it cycles through the available addressing modes: page relative, repo relative, http://, file://

The completion list shows all files that can be represented in the selected addressing format.

I am considering showing files that cannot be represented in the selected format but highlighted in another color so that they are seen but distinct.

**Comment by vsch** [comment] 2017-03-10 18:27
@holgerbrandl, correction to above the external module is under VCS, removing the VCS root from config removes all files from completions. While under VCS the links complete but only in non-http format.

I am going to investigate the logic that causes the latter. I will also try to figure out if there is a logical solution to resolving modules which are outside the project directory and not under VCS.

**Comment by holgerbrandl** [comment] 2017-03-10 19:50
I'm not sure if I can follow. The file that I'd like to reference is in the same directory. This directory was added as a content root to the idea module, and all it's files and subdirectory are correctly listed in the project tool-window. From a my naive user perspective it should imho not matter if VCS if used or not. The completion provider should "just" get the parent directory of the markdown file and add all its contents to the suggestion list.

**Comment by vsch** [comment] 2017-03-10 20:34
@holgerbrandl, yes I concur. It took me a long time to wrap my brain around the difficulty of mapping file system path to GitHub link variations through many iterations of implementation (four or five if I remember). Another reason is historical evolution of the code with some limitations left in from previous implementations.

The main difficulty comes from the fact that link resolution is done assuming GitHub repository, Wiki rules and one to many mapping from file path to link address. This makes it dependent on which file contains the link, the link target file location (another VCS root, Wiki, etc) and target file type. 

It also depends on the link address format being used. Not all address formats and link types (images have their own limitations) can access all files. GitHub has all kinds of rules for link resolution in documents and wiki pages to other documents, wiki pages, non-image files and image files.

The issue arises on what to do when VCS root is not available. The plugin needs to know what is the root directory for the file containing the link so that all files it can possibly link (in any addressing mode) are filtered in. Link address format filtering, wiki link and image link filtering is done as a second step.

Right now the plugin uses the project root directory when there is no VCS root to work with. The reason this was chosen is to allow inter-module linking within a project and because I naively assumed modules will be under the project root.

One solution is to add the Module root directory for the file's completions if the module root is not under the project root, in addition to the project root for inter-module linking. This way all files in the module will be accessible but files under the project root will be accessible only if using `file://...` address format or they are under VCS and link address format is `http://...`.

Repo relative address format can apply to files within the same directory root (module or project) and page relative needs to be limited to a known base root other than `/` which will include the whole file system. I did not consider `/` as a reasonable limit for accessing files, but the plugin uses IDE file index instead of scanning the file system like it used to, therefore limitation can be removed.

This explanation has given me ideas to address with modules outside the project root and not under VCS. I will do some exploratory code changes and tests. I will let you if I find a solution that is workable without rewriting the whole link resolution implementation. 

My fear is that it will churn a lot of brittle code handling the link to file and file to link resolution logic. It may require major refactoring of this code. A lot of special conditions were added to address bugs since the last clean-up and I am not sure that the code will support these changes without deteriorating into an unmanageable mess.

**Comment by vsch** [comment] 2017-03-11 05:38
@holgerbrandl, I think I got it to work in a way that makes sense.

EAP available. Now it will handle inter vcs-root links if file:// or http:// and also handle modules not under project root. Intra module links can be page or repo relative or file://. If it is under vcs with remote URL then also http://.

Also fixed a lot of bugs where the code assumed that an http:// link was either current file's vcs-root or not targeting a project file. Now Inter-vcs-root http:// links resolve to a project file even if the module is not under the project directory.

I could have introduced a bug or two. If you encounter a problem please let me know.

**Comment by holgerbrandl** [comment] 2017-04-21 12:20
With  v2.3.5.8 `file://` links are still flagged in red whereas `http://` ones are not
![image](https://cloud.githubusercontent.com/assets/200952/25277064/77dc031a-269d-11e7-9cd5-e450430e8593.png)
It does not make a difference if they start with `file:///` or just `file://`.

The referenced file exists but does not belong to any IJ module.

**Comment by vsch** [comment] 2017-04-21 17:33
@holgerbrandl

**Comment by vsch** [comment] 2017-04-21 17:35
@holgerbrandl, the http: links are only checked for validity if they point to a GitHub project URL. Otherwise they are not checked.

The file:// link shows that it does not exist because it points to a file not under the project root so the IDE indexing does not cover this file.

**Comment by holgerbrandl** [comment] 2017-04-21 20:43
Wouldn't the regular java.io.File API to test local URLs? I don't understand why all references must sit under a project root. Having an external link is not an error, and should imho no displayed as such (i.e. b by tagging it as missing/unresolved).

**Comment by holgerbrandl** [comment] 2017-04-21 20:52
Wouldn't the regular java.io.File API able to test local URLs? I don't understand why all references in a markdown file must sit under a project root. In my experience there's not just source code but always also some not-vcs-controlled data which needs to referenced. Having an external link is not an error, and should imho not be displayed as such (i.e. by tagging it as missing/unresolved).

**Comment by vsch** [comment] 2017-04-22 01:17
@holgerbrandl, you are right about not displaying as an error since no checking can be reliably done. Going to the File test method would only solve the error highlight issue and not help with completions which require indexed files.

I will add a test for file:// prefixed links that are not part of any module root to exclude these from being highlighted as errors.

**Comment by vsch** [comment] 2017-04-22 01:50
EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.

**Comment by holgerbrandl** [comment] 2017-04-22 10:03
Thanks for the quick update.

> @holgerbrandl, you are right about not displaying as an error since no checking can be reliably done. Going to the File test method would only solve the error highlight issue and not help with completions which require indexed files.

I don't fully agree: file URLs always correspond to absolute filesystem paths, so plugin could actually indicate if a file URL is valid or not. File URLs referring to non-existing files could/should imho be marked in red (second example in screenshot). 

![image](https://cloud.githubusercontent.com/assets/200952/25303409/ac7353ca-2752-11e7-929f-9b8f044ac930.png)

**Comment by vsch** [comment] 2017-05-02 22:18
@holgerbrandl, latest eap 2.3.7.2 will highlight these types of links if the file is missing. Intentions on these links are not supported. Only missing highlight is implemented.

**Comment by holgerbrandl** [comment] 2017-05-03 07:03
I've just tried it and it works like charm. Thanks for your great support.

**Closed** 2017-07-18 01:39 UTC
Labels: bug, fix available, fixed for next release
