### ISSUE TITLE
auto-move in preview to match source code cursor position

### ISSUE THREAD

**Issue by chilek** [vsch/idea-multimarkdown#743] opened 2019-04-23 09:45 UTC
Version used: 2.8.4
My MD document has size 169798 bytes and uses TOC.
Is there some line/size limit in source code to get working preview in right panel with auto cursor position?

**Comment by chilek** [comment] 2019-04-23 09:51
Changed _Markdown/Preview/Preview browser_ to _Swing_ and then back to _JavaFX WebView_ and automatic cursor positioning works again ;-)

**Comment by chilek** [comment] 2019-04-23 11:26
After PHPStorm restart problem appears again.

**Comment by chilek** [comment] 2019-04-23 14:44
Problem is reproducible - switching preview renderer from _JavaFX WebView_ to _Swing_ and back fixes the problem until next PHPStorm restart.

**Comment by chilek** [comment] 2019-04-23 14:52
Upgrade to EAP 2.8.4.20 version doesn't fix the problem.

**Comment by vsch** [comment] 2019-04-23 20:25
@chilek, I will try to figure out what is causing this. It appears to be related to an unstable settings state being restored on IDE startup. I am trying to figure out what exactly are those setting conditions. Duplicate #735

**Comment by vsch** [comment] 2019-04-23 22:00
@chilek, I released an EAP version with added logging to the code changing the panel initialization and changes to settings in the hope that extra information will help me figure out what set of conditions cause this issue.

To enable the extra logging to the IDE log file you need to add a line:

    com.vladsch.idea.multimarkdown.editor.htmlPrep-rendering:trace

to the IDE Debug Log Settings in the main menu under `Help` > `Debug Log Settings...`

I want to see if there is something in the initialization of rendering profile for the preview editor that is causing this behaviour.

You can either send me the log by e-mail or extract log entries which have `DEBUG` in the log type.

**Comment by chilek** [comment] 2019-04-24 06:19
@vsch here is debug log:

```
2019-04-24 08:17:07,600 [   7785]  DEBUG - down.editor.htmlPrep-rendering - initialized rendering profile: '' panel info: com.vladsch.idea.multimarkdown.editor.javafx.html.panel, css: com.vladsch.idea.multimarkdown.editor.javafx.html.css 
2019-04-24 08:17:09,624 [   9809]  DEBUG - down.editor.htmlPrep-rendering - OnProjectSettingsChange updateRenderingProfile: Project '/home/chilek/PhpstormProjects/lmsdemo' lmsdemo, false, '' com.vladsch.idea.multimarkdown.editor.javafx.html.panel 
2019-04-24 08:17:09,624 [   9809]  DEBUG - down.editor.htmlPrep-rendering - updateRenderingProfile: Project '/home/chilek/PhpstormProjects/lmsdemo' lmsdemo, false, '' com.vladsch.idea.multimarkdown.editor.javafx.html.panel 
2019-04-24 08:17:09,624 [   9809]  DEBUG - down.editor.htmlPrep-rendering - after update: '' com.vladsch.idea.multimarkdown.editor.javafx.html.panel 
2019-04-24 08:17:37,603 [  37788]  DEBUG - down.editor.htmlPrep-rendering - OnProjectSettingsChange updateRenderingProfile: Project '/home/chilek/PhpstormProjects/lmsdemo' lmsdemo, false, '' com.vladsch.idea.multimarkdown.editor.swing.html.panel 
2019-04-24 08:17:37,603 [  37788]  DEBUG - down.editor.htmlPrep-rendering - updateRenderingProfile: Project '/home/chilek/PhpstormProjects/lmsdemo' lmsdemo, false, '' com.vladsch.idea.multimarkdown.editor.swing.html.panel 
2019-04-24 08:17:37,603 [  37788]  DEBUG - down.editor.htmlPrep-rendering - after update: '' com.vladsch.idea.multimarkdown.editor.swing.html.panel 
2019-04-24 08:17:46,283 [  46468]  DEBUG - down.editor.htmlPrep-rendering - OnProjectSettingsChange updateRenderingProfile: Project '/home/chilek/PhpstormProjects/lmsdemo' lmsdemo, false, '' com.vladsch.idea.multimarkdown.editor.javafx.html.panel 
2019-04-24 08:17:46,283 [  46468]  DEBUG - down.editor.htmlPrep-rendering - updateRenderingProfile: Project '/home/chilek/PhpstormProjects/lmsdemo' lmsdemo, false, '' com.vladsch.idea.multimarkdown.editor.javafx.html.panel 
2019-04-24 08:17:46,283 [  46468]  DEBUG - down.editor.htmlPrep-rendering - after update: '' com.vladsch.idea.multimarkdown.editor.javafx.html.panel 
```

I hope will be helpfull.

**Comment by vsch** [comment] 2019-04-25 01:11
@chilek, unfortunately there is nothing in this information that is out of the ordinary.

Can you please add the following to the debug trace settings to add traces for actual scroll pos invocation:

```
com.vladsch.idea.multimarkdown.editor.htmlPrep-rendering:trace
com.vladsch.idea.multimarkdown.editor.javafx-scroll:trace
com.vladsch.idea.multimarkdown.editor.htmlPrep-details:trace
com.vladsch.idea.multimarkdown.editor.javafx:trace
```

I would really appreciate the debug log trace for condition when the scroll is not working (before you toggle preview type) and working (after you toggle preview type) separately identified so that I can see what conditions are causing the difference.

I wish I could reliably duplicate this so that I would not have to bother you with this. However, I am glad that you have ability to reliably duplicate this because until now this was always spurious and after being fixed would not reliably show up.

You should either remove these debug entries afterwards or prefix them with a dash `-` to remove these traces since they can generate a fair bit of logging when editing markdown files.

**Comment by chilek** [comment] 2019-04-25 07:53
Please give me your email address to which I'll send two log files which are result of two PHPStrorm sessions: one with not working preview feature, and other in which works after change PreviewRenderer to Swing and then back to JavaFX WebView.

**Comment by vsch** [comment] 2019-04-25 20:05
@chilek, you can use my e-mail in GitHub profile: vladimir / vladsch.com

**Comment by chilek** [comment] 2019-04-26 05:49
@vsch I've sent it already.

**Comment by vsch** [comment] 2019-04-27 17:04
@chilek, thank you. I will be going through the logs to isolate differences and figure out the cause of the bug.

**Comment by vsch** [comment] 2019-04-28 16:46
@chilek, I could see a difference in the logs. Mainly, the JavaFX panel notification that page load request completes is never seen by the plugin. This causes initialization for scroll sync code to never be run.

I could not see any settings related causes for this. The only thing I found was that initial JavaFX panel creation had a scheduling delay of 1ms while subsequent panel creations, which occur when preview type changes, had a delay of 10ms. This difference could cause timing differences in event processing.

It is a stretch to say that I am sure that this is the cause of the problem. However, this was the only difference that I can see why subsequent JavaFX panel creations work while the original does not.

I updated the EAP channel with a version which uses the same panel creation delay. On my system it works the same way as before, however, since this is timing dependent then all system differences, including CPU horse power, system memory, loading, etc. could have an effect.

Please let me know if this fixes the issue or you are still seeing the same behaviour.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)

**Comment by chilek** [comment] 2019-05-07 07:45
Unfortunately on 2.8.4.26 problem still persists :(

**Comment by chilek** [comment] 2019-05-07 07:46
Maybe you will be able to re-play problem with my custom MD file? Shall I send it to you?

**Comment by vsch** [comment] 2019-05-07 12:14
@chilek, yes please send it to me. Anything that could help me duplicate this issue would be greatly appreciated.

**Comment by chilek** [comment] 2019-05-07 13:55
Sent.

**Comment by vsch** [comment] 2019-05-08 15:34
@chilek, on my system the file works without scrolling issues. 

I think this could be OS or JRE related. 

What is the OS you are running on?

Is the JRE for the IDE is JetBrains bundled or Oracle?

**Comment by chilek** [comment] 2019-05-08 15:38
@vsch: have you tried close and re-open ide twice or more? It can appear after some ide restarts.

My environment:
```
=== About ===
Build version: PhpStorm 2019.1.1 Build #PS-191.6707.66 April 17, 2019
Java version: 1.8.0_202-release-1483-b44amd64
Operating System: Linux (5.0.11-300.fc30.x86_64, amd64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o

=== System ===
Number of CPU: 8
Used memory: 748Mb 
Free memory: 883Mb 
Total memory: 1631Mb 
Maximum available memory: 1631Mb

=== Displays ===
Displays: 
Display 0: 2560x1440; scale: 1,00

=== Plugins ===
Custom plugins: [Markdown Navigator (2.8.4.26)]
Disabled plugins:[IntelliJ Configuration Script (191.6707.66), Markdown support (191.6707.66)]

```

**Comment by vsch** [comment] 2019-05-08 16:13
@chilek, tried it on UBUNTU 18.04 under parallels desktop on the mac and no luck in duplicating it.

The about information on my test setup is:

```
IntelliJ IDEA 2019.1.2 (Community Edition)
Build #IC-191.7141.44, built on May 7, 2019
JRE: 1.8.0_202-release-1483-b49 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-45-generic
```

I suspect that the issue is with initialization of JavaFX WebView which for some reason does not work properly when the IDE powers up. I will keep trying to figure out what set of conditions cause this.

It is not straight forward because the it is all async code switching between AWT thread and JavaFX thread. Hard synchronization is not an option because it will block AWT thread and hang the IDE. Because of soft-synchronization there is a timing issue which causes the initialization to fail.

**Comment by vsch** [comment] 2019-05-08 16:44
@chilek, the same with PhpStorm under UBUNTU

```
PhpStorm 2019.1.2
Build #PS-191.7141.52, built on May 8, 2019
Licensed to Vladimir Schneider
Subscription is active until October 10, 2019
JRE: 1.8.0_202-release-1483-b49 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-45-generic
```

**Comment by chilek** [comment] 2019-05-10 05:30
> the same with PhpStorm under UBUNTU

you mean you have describe problem with above platform or not?

**Comment by chilek** [comment] 2019-05-10 10:05
After update to 2019.1.2:
```
=== About ===
Build version: PhpStorm 2019.1.2 Build #PS-191.7141.52 May 8, 2019
Java version: 1.8.0_202-release-1483-b49amd64
Operating System: Linux (5.0.11-300.fc30.x86_64, amd64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o

=== System ===
Number of CPU: 8
Used memory: 774Mb 
Free memory: 222Mb 
Total memory: 997Mb 
Maximum available memory: 1631Mb

=== Displays ===
Displays: 
Display 0: 2560x1440; scale: 1,00

=== Plugins ===
Custom plugins: [Markdown Navigator (2.8.4.26)]
Disabled plugins:[IntelliJ Configuration Script (191.7141.52), Markdown support (191.7141.52)]

```

Problem still persists.

**Comment by vsch** [comment] 2019-05-10 16:44
@chilek, on my system all tested IDEs work on both OS X and UBUNTU. Next I will try to duplicate the memory configuration to see if that affects the timing and the result.

**Comment by chilek** [comment] 2019-05-17 16:51
Althout I mentioned that it resolved it's not truth. After PHPStorm restart the problem came back :(

**Comment by vsch** [comment] 2019-05-17 17:07
@chilek, how have you been updating PhpStorm versions? Using JetBrians toolbox or via IDE update downloading and applying patches?

I have found previous that applying patches in some cases results in messed up installations which were only fixed by downloading and installing a new version. In some cases deleting application support files and re-installing plugins.

No idea what caused it by since I stopped updating IDEs and resort to using JetBrains Toolbox which download full application and does not resort to updating via patches.

**Comment by chilek** [comment] 2019-05-20 16:42
Thanks for valuable hint? I'll try to reinstall PhpStorm using full-package? Is JetBrain toolbox accessible on Linux?

**Comment by vsch** [comment] 2019-05-21 13:18
@chilek, yes. I am running it in my parallels desktop UBUNTU.

**Comment by chilek** [comment] 2019-05-21 13:30
I've downloaded it and lauched and it works.

**Comment by vsch** [comment] 2019-05-21 13:31
@chilek, do you mean Toolbox works or PhpStorm scroll synchronization?

**Comment by chilek** [comment] 2019-05-21 13:33
@vsch: toolbox.

**Comment by vsch** [comment] 2019-12-04 00:10
@chilek, I think I found the bug. There was an uncaught JS script exception which was silently absorbed by Java code during initialization. It was causing the JS not to initialize properly and not have any ability to sync source or generate other JS events for Java use.

It was a real PITA to find and I stumbled on it almost by accident while working on something else. Have not had scroll sync issues since then.

I will mark this as fixed for next release but when you do try it please let me know if it is still an issue on your system.

**Comment by chilek** [comment] 2019-12-04 07:58
I have selected EAP update channel in PHPStorm and 2.9.7.20 installed.
Is it enough to check fix or should I do something else?

**Comment by vsch** [comment] 2019-12-04 10:29
@chilek, sorry I was not clear enough that it is fixed for the next release and is not yet available.

The last EAP release does not have the scrolling issue fixed. The fix was made after Oct 4 but since then I was unable to make a release due to major rework of code to separate basic and enhanced features. 

I was about two weeks away from completing that, when 2019.3 Beta came out and I discovered that new Kotlin run-time breaks an old library used by the plugin. I have been working around the clock to get that library replaced. It was used practically everywhere throughout the code.

I am running a dev build which does not have wrap on typing working properly. To be more accurate, the wrapping works perfectly and is 40x faster than old code but caret position recovery after text is wrapped is broken. Which means that every time the lines are wrapped the caret jumps somewhere nearby, making it impossible to continue typing without restoring the caret position. Effectively typing with the mode enabled is impossible.

I will make an EAP release probably within a week. I will post an update here as soon as the release is available. BTW, the next release is a **huge** improvement in performance.

**Comment by chilek** [comment] 2019-12-04 10:35
@vsch thanks a lot for such good news - I'm looking forward for next release! ;-)

**Closed** 2019-12-19 22:37 UTC
Labels: bug, fixed for next release

**Comment by vsch** [comment] 2019-12-20 16:35
@chilek, plugin version 2.9.9 is available in JetBrains Marketplace for IDE version 2019.3 or later (one can hope).

**Comment by chilek** [comment] 2019-12-20 16:46
I've updated plugin before the moment. I'll let you know if I observe the same problem (I hope not). Thanks for great support!
