### ISSUE TITLE
Creating list from selection

### ISSUE THREAD

**Issue by Melodyn** [vsch/idea-multimarkdown#641] opened 2018-10-08 08:07 UTC
Create a list from the selected text obtained only if there are two line breaks. Is it possible to make so that it worked on one line? Visualization: https://youtu.be/D4PPR83ImpI

----

Создание списка из выделенного текста получается только при наличии двух переносов строки. Можно ли сделать так, чтобы это работало при одном переносе строки?

**Comment by vsch** [comment] 2018-10-08 18:14
@Melodyn, the reason is that without blank lines it is a single paragraph not 3 paragraphs. The action converts selected markdown elements to list items. Splitting a paragraph into separate list items for each line would require a separate action.

However, you can use the IDE multiple carets to get what you want with a few keystrokes. Instead of selecting lines, use clone caret then type the list item prefix:

![multicaretitems](https://user-images.githubusercontent.com/10299086/46626072-3be57000-cb04-11e8-8e15-3f175a6f5b89.gif)

Or alternately, use insert item on ENTER and join lines but that takes more keystrokes

![splititems](https://user-images.githubusercontent.com/10299086/46626078-40118d80-cb04-11e8-9cfa-bb4b180224bd.gif)


I have clone caret actions assigned to variation of the up/down keys to have quick access.

<img width="929" alt="screen shot 2018-10-08 at 2 11 14 pm" src="https://user-images.githubusercontent.com/10299086/46626089-44d64180-cb04-11e8-946b-6738877c239a.png">

**Comment by Melodyn** [comment] 2018-10-09 06:53
Yes, I know how to organize the list without the help of the plugin... however this is not consistent with the expectations of the plugin. For example, here, on github, the list is created as expected:
![yea](http://g.recordit.co/Whd7mG4nNR.gif)
My vote for the expected behavior, if possible :)

----

Да, я знаю как можно организовать список без помощи плагина... однако, это не соответствует ожиданиям от плагина. Для примера, здесь, на гитхабе, список формируется ожидаемым образом. Мой голос за ожидаемое поведение, если это возможно :)

**Comment by vsch** [comment] 2018-10-15 08:28
@Melodyn, I will add an action to the toolbar to split individual lines in a paragraph to separate list items.

I will have to play with the code to see how to implement toggling with this action. The catch is that once converted to list items, removing the list items will convert the each list item to its own paragraph. I may remove the list item prefix and not convert to paragraph, that way toggling will result in original text.

**Comment by vsch** [comment] 2018-10-16 11:52
@Melodyn, btw implementing this for general case is harder than would seem since it has to work with elements in block quotes and other contexts.

Try using GitHub list toggle with block quoted text and it results in counter intuitive behaviour.

```
> this is some text
> this is some text
> this is some text
```

Selecting all lines adds prefix before the block quote. Putting the caret after `>` and toggling list item results in a mess with extra blank lines.

**Comment by Melodyn** [comment] 2018-10-16 14:18
As I see it, the current implementation of the plug-in also does not create lists inside the block of quotation. Therefore, you do not lose anything ... If I correctly understood the subject of conversation.
![image](https://user-images.githubusercontent.com/26752238/47022869-1b05c600-d167-11e8-8697-2f06c0b814cb.png)

PS
For me, this functionality is not critical, I set up a macro for it. If it does not work, I think no one will be upset :)

----

Как я вижу, текущая реализация плагина тоже не создаёт списки внутри блока цитаты.  Поэтому вы ничего не теряете. Если я правильно понял предмет разговора.

PS
Для меня этот функционал не критичен, я настроил для него макрос. Если не получится, думаю, никто не расстроится :)

**Comment by vsch** [comment] 2018-10-16 15:38
@Melodyn, it does not create list items because you do not have the first line of the paragraph selected and the current implementation only adds list items to the paragraph. Which is inline with the operation of the action.

Similarly, the new action will have to handle it for any line selected, including in block quotes.

From past experience, if the functionality is not general enough then someone will complain that it does not work properly.

**Comment by vsch** [comment] 2018-12-15 01:04
@Melodyn, added as a special case if the selection contains a single
  paragraph then all lines in the paragraph will be converted to list items, toggling list item
  markers again will convert them back to a block of lines. Removal of list item prefixes will
  convert a block of selected list items which consist of a single line of text and no
  intervening blank lines to a block of text. In all other cases the selected elements will be
  converted to list item per paragraph and removal of list item prefixes will add blank lines
  between resulting paragraphs.

EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)

**Closed** 2019-02-03 22:43 UTC
Labels: enhancement, fix available, fixed for next release
