### ISSUE TITLE
It crashes IDEA w/o any warnings

### ISSUE THREAD

**Issue by kfuzaylov** [vsch/idea-multimarkdown#55] opened 2015-10-28 10:37 UTC
Today i have updated to latest version and my idea starts to crash. 
Couple times idea showed "out of memory" popup, but memory was enough.
I have removed this plugin and idea works fine.

**Comment by vsch** [comment] 2015-10-28 13:57
@kfuzaylov can you please let me know the JetBrains IDE, Build number and the JRE that it is running in to help me duplicate the and debug the problem. In the past a sudden crash happened in the JavaFX native libraries but it sound like a different problem.

Is there any log information about where the crash is occurring?

**Comment by LordWeedlle** [comment] 2015-10-28 16:57
I got exactly the same issues, got IDE randomly stopping, and got one time like 5-6 in chain 'out of memory' pop-ups.
I'm actually using PhPStorm 9.0.2
Build #PS-141.2462
I uninstalled the plugin to prevent any IDE crash, I'll wait until it's fixed to use it again ^^

**Comment by vsch** [comment] 2015-10-28 18:18
I switched from PhpStorm 10 Preview to 9.0.2 build PS-141.2462 so I can try and duplicate this but no luck. I tried both the old Swing and JavaFX previews both work.

Could be JRE and OS differences. I am running Mac OS X 10.10.5 Yosemite. **What OS are you running on and what Java version?** JRE is shown in the PhpStorm About dialog

<img width="404" alt="screen shot 2015-10-28 at 2 09 51 pm" src="https://cloud.githubusercontent.com/assets/10299086/10798363/9d24dee6-7d7d-11e5-842a-fc95cb086c60.png">

As for the HTML Text tab it should display if it is enabled in settings. The HTML Preview and HTML Text are the same class with the only difference being a flag: one instantiates JPanel with HTMLEditorKit or JavaFX WebView and the other the Open API IntelliJ Text Editor.

<img width="1107" alt="screen shot 2015-10-28 at 1 57 25 pm" src="https://cloud.githubusercontent.com/assets/10299086/10798175/bfc515f2-7d7c-11e5-986d-96dacf0995fc.png">

The other issue could be a lot of markdown files in the project tree. However, I tested it in a project with 100,000+ files total and 3800+ markdown files and other than a few seconds delay when doing rename refactoring of a markdown file with reference search by the IDE I did not have any delays. The latest version uses the IntelliJ FileBasedIndex to get the markdown file list instead of scanning the VirtualFile system source roots. The latter was problematic and a memory hog, the former is very efficient.

It is possible that some other project specific setting is causing the issue. I have had issues when the cached indices were corrupted during debug but that was resolved by invalidating indexes and restarting so the IDE re-indexes the project.

I'll keep trying to figure out what could be causing this issue and let you know.

**Comment by LordWeedlle** [comment] 2015-10-29 08:13
Hello,
I'm running Windows 7 and JRE 1.8.0_51-b16 x86 (same as yours but 32bits version).
I don't got so much markdown files in the project (I know only one .md file).

Thx for the tip to enable the HTML preview =)

**Comment by vsch** [comment] 2015-10-29 16:13
@LordWeedlle thanks for the OS update. As far as markdown file count is concerned, it is not just the files that are in your project directly but also in the libraries that are in the project. The test project I use came from someone who had over 3800 markdown files in the libraries. That should not cause a hang  or large memory footprint since the plugin does not store the list.

I will keep digging on my end. If you come across anything that sheds light on what configuration on your project causes this please let me know. I need to duplicate this or at least find out in what part of the code the problem occurs. Needless to say, being able to duplicate the issue goes a long way to resolving it.

**Comment by breandan** [comment] 2015-11-24 16:34
I am running WS-143-870.2 with idea-multimarkdown 1.2.2 and this noticed this error in the log after the crash occurred:

```
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:646)
	at com.vladsch.idea.multimarkdown.util.FilePathInfo.resolveLinkRef(FilePathInfo.java:499)
	at com.vladsch.idea.multimarkdown.util.FileReference.resolveExternalLinkRefNoWiki(FileReference.java:245)
	at com.vladsch.idea.multimarkdown.util.FileReference.resolveExternalLinkRef(FileReference.java:251)
	at com.vladsch.idea.multimarkdown.psi.impl.MultiMarkdownReferenceLinkRef.getMultiResolveResults(MultiMarkdownReferenceLinkRef.java:99)
	at com.vladsch.idea.multimarkdown.psi.impl.MultiMarkdownReference.multiResolve(MultiMarkdownReference.java:100)
	at com.vladsch.idea.multimarkdown.language.MultiMarkdownLineMarkerProvider.collectNavigationMarkers(MultiMarkdownLineMarkerProvider.java:84)
	at com.intellij.codeInsight.daemon.RelatedItemLineMarkerProvider.collectNavigationMarkers(RelatedItemLineMarkerProvider.java:48)
	at com.intellij.codeInsight.daemon.RelatedItemLineMarkerProvider.collectSlowLineMarkers(RelatedItemLineMarkerProvider.java:39)
	at com.intellij.codeInsight.daemon.impl.SlowLineMarkersPass.addLineMarkers(SlowLineMarkersPass.java:78)
	at com.intellij.codeInsight.daemon.impl.SlowLineMarkersPass.doCollectInformation(SlowLineMarkersPass.java:65)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1169)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

Full log [uploaded here](https://gist.github.com/breandan/3a5ec290688105ccb163).

**Comment by vsch** [comment] 2015-11-24 16:40
Thanks.

Best regards,


Vladimir.

**Comment by markwoon** [comment] 2015-12-04 18:33
I'm having similar issues.  After updating to the IDEA Ultimate 15.0.2 RC attempting to open a markdown file causes IDEA to hang.

**Comment by vsch** [comment] 2015-12-04 18:44
@markwoon, any markdown file or just a particular one? I had one issue where the hang was caused by parser getting confused and going into an infinite loop waiting for a lexer token without checking for EOF, but that was in one particular case and it was fixed a release or two ago.

I am running the same version IDEA Ultimate on the Mac.

Would it be possible for you to launch the IDE in an IDEA debug session as if you are debugging a plugin? That way you can take a snapshot of the threads after it hangs. 

<img width="184" alt="screen shot 2015-12-04 at 1 40 18 pm" src="https://cloud.githubusercontent.com/assets/10299086/11597908/c15642ce-9a8c-11e5-8041-1005afb46e89.png">

It would give me more to work with as far as the location of the errant code. I cannot duplicate this otherwise I would not have released it. ;)

**Comment by markwoon** [comment] 2015-12-04 18:47
@vsch Seems to be any file.  Forgot to mention that this started happening after I updated to the latest version of the plugin when prompted this morning.

How do I run IDEA in debug mode?

**Comment by vsch** [comment] 2015-12-04 19:29
The new version has completely reworked link resolving logic so it is possible that there is an issue but I am running over 4000 tests on about 300 link address variations so it would not be common, famous last words. :)

To run the IDEA in debug, the easiest way is to create a dummy plugin project. Nothing to add just the defaults.

1. File -> New -> Project ... 

    ![screen shot 2015-12-04 at 1 59 07 pm](https://cloud.githubusercontent.com/assets/10299086/11598407/afe1a922-9a8f-11e5-9422-a6e61003cfec.png)

2. Click Next, and either change the default `untitled` project name and location or leave them the same.

3. Click Finish.

4. Setup a Plugin JDK for the project by  selecting Default Project Structure...

    ![screen shot 2015-12-04 at 2 05 36 pm](https://cloud.githubusercontent.com/assets/10299086/11598488/27856536-9a90-11e5-9fda-e9fa3216f766.png)

5. Create a plugin platform SDK by selecting SDKs and clicking on the + to add one:

    ![screen shot 2015-12-04 at 1 57 27 pm](https://cloud.githubusercontent.com/assets/10299086/11598515/55ea8fdc-9a90-11e5-926b-810bbfa5a5b7.png)
 
6. In the dialog that comes up take the default and click OK. It will be the IDEA version that you are running at the moment.

    ![screen shot 2015-12-04 at 1 57 37 pm](https://cloud.githubusercontent.com/assets/10299086/11598536/83e51d94-9a90-11e5-8981-6a8b1fcb6690.png)

7. Click Apply to make sure the new SDK is saved in the config. Don't hit OK, we still need to change a few more things.

    ![screen shot 2015-12-04 at 1 57 55 pm](https://cloud.githubusercontent.com/assets/10299086/11598587/d4abe596-9a90-11e5-8e03-a34a75787713.png)

8. Select the Project Settings > Project and in the Project SDK drop down select the SDK you just created:

    ![screen shot 2015-12-04 at 1 58 18 pm](https://cloud.githubusercontent.com/assets/10299086/11598605/f042cfd6-9a90-11e5-91d7-7af4e423decf.png)

9. Hit OK. The project is now set up and after some indexing operations you should see the plugin ready for debugging, 

10. If you have the tool bar enabled,

    ![screen shot 2015-12-04 at 1 59 51 pm](https://cloud.githubusercontent.com/assets/10299086/11598708/7406fcca-9a91-11e5-80e3-616d53133b0f.png)

    or select debug from the run menu

    ![screen shot 2015-12-04 at 2 14 57 pm](https://cloud.githubusercontent.com/assets/10299086/11598720/8792d32c-9a91-11e5-9521-af341fa989e1.png)

    This should launch the IDEA under debug session in the IDEA. How cool is that!

    Note that the IDEA under debug will be launched in a sandbox so it will think it is a fresh installation. You can tell it to load your config from existing preferences or just take the default. We only want to take a snapshot. 

11. Once it comes up install MultiMarkdown by downloading it in plugins. When it asks to restart hit Postpone. If you restart then it will try to restart without the debugger.

12. Quit the IDEA being debugged and re-launch the debug session as in step 10.

13. Now open your project and then a markdown file. 

14. Once it hangs, in the IDEA doing the debugging in the debug tool window Click the camera button.
That will take a snapshot of all threads

    ![screen shot 2015-12-04 at 2 21 07 pm](https://cloud.githubusercontent.com/assets/10299086/11598918/889f8cbe-9a92-11e5-83b8-518904497282.png)

15. Then  Click on the export to file and send the file to me vladimir at vladsch.com

If you run into problems just let me know. IDEA can be difficult to figure out at first. I still remember that it took me 4 attempts at getting the plugin dev setup. First three times I gave up after 3 to 4 hours of trying. I did not do Java development for over 10 years so most of it was forgotten and the terminology was alien to me.

**Comment by markwoon** [comment] 2015-12-04 21:45
Thanks for the detailed instructions.

I stepped through it and could not trigger the problem.  So I blew away my settings/preferences and started IDEA and so far, so good.

**Comment by vsch** [comment] 2015-12-04 21:51
@markwoon thank you very much for taking the time to help me debug this issue.

It was most likely caused stale caches. I keep forgetting to bump up the version for the WordsScanner used by the FindUsagesProvider to force re-indexing when a new plugin is installed, just to be on the safe side.

I will add it to my release check list.

**Closed** 2016-01-04 19:47 UTC
Labels: cannot duplicate, ☹ bug

**Comment by youyanghuang** [comment] 2016-05-06 10:23
@vsch 
Today I upgrade the plugin to **the latest version 1.5.0**, the IDE IDEA crashes w/o any error info.My os is 
win10 64bit.
And when I try to add the idea vm Xmx size to 1024m,  it crashes too.
The last many lines of idea log file are below:
>2016-05-06 17:39:39,980 [ 360740]   INFO - ea.multimarkdown.editor.javafx - onScroll: [1] window scrolled to 0, 0 
2016-05-06 17:39:44,408 [ 365168]   INFO - ea.multimarkdown.editor.javafx - onScroll: [1] window scrolled to 0, 1240 
2016-05-06 17:39:47,176 [ 367936]   INFO - ea.multimarkdown.editor.javafx - onScroll: [1] window scrolled to 0, 1275

**Comment by vsch** [comment] 2016-05-06 13:55
@youyanghuang, from the log it shows that the JavaFX preview scrolled down the page as the last action. Scrolled down 1275 pixels, which is about a single page.

Previously these types of crashes occurred in JavaFX native libraries when displaying images. However, this only in OS X, not windows. 

**Is it happening in a particular file?**

Other causes have been corrupted cache files. **Can you "Invalidate Caches/Restart" which has previously resolved mysterious crashes.**

**Can you let me know the IDEA version and the JRE version that you are running?**

**Comment by vsch** [comment] 2016-05-07 13:48
@youyanghuang, did you make any progress on the issue?

**Comment by youyanghuang** [comment] 2016-05-09 01:47
It still crashes after **"Invalidate Caches/Restart"**.
My IDEA version is **build #IU-141.1532.4, 18 Jun 2015 00:00**.
The JRE version is built-in, which is **1.8.0_40-b26 (Oracle Corporation)**
Today it throws new exception below:
> 2016-05-09 09:36:39,925 [   2424]   INFO - llij.ide.plugins.PluginManager - Cannot load C:\Users\xxx\.IntelliJIdea14\config\plugins\idea-multimarkdown 
com.intellij.util.xmlb.XIncludeException: java.io.FileNotFoundException: \META-INF\version-notes.xml (系统找不到指定的路径。)
	at com.intellij.util.xmlb.JDOMXIncluder.parseRemote(JDOMXIncluder.java:344)
	at com.intellij.util.xmlb.JDOMXIncluder.resolveXIncludeElement(JDOMXIncluder.java:231)
	at com.intellij.util.xmlb.JDOMXIncluder.resolveNonXIncludeElement(JDOMXIncluder.java:358)
	at com.intellij.util.xmlb.JDOMXIncluder.resolve(JDOMXIncluder.java:192)
	at com.intellij.util.xmlb.JDOMXIncluder.doResolve(JDOMXIncluder.java:177)
	at com.intellij.util.xmlb.JDOMXIncluder.doResolve(JDOMXIncluder.java:99)
	at com.intellij.util.xmlb.JDOMXIncluder.resolve(JDOMXIncluder.java:84)
	at com.intellij.util.xmlb.JDOMXIncluder.resolve(JDOMXIncluder.java:80)
	at com.intellij.ide.plugins.IdeaPluginDescriptorImpl.readExternal(IdeaPluginDescriptorImpl.java:171)
	at com.intellij.ide.plugins.IdeaPluginDescriptorImpl.readExternal(IdeaPluginDescriptorImpl.java:167)
	at com.intellij.ide.plugins.IdeaPluginDescriptorImpl.readExternal(IdeaPluginDescriptorImpl.java:180)
	at com.intellij.ide.plugins.PluginManagerCore.loadDescriptorFromDir(PluginManagerCore.java:571)
	at com.intellij.ide.plugins.PluginManagerCore.loadDescriptor(PluginManagerCore.java:627)
	at com.intellij.ide.plugins.PluginManagerCore.loadDescriptors(PluginManagerCore.java:721)
	at com.intellij.ide.plugins.PluginManagerCore.a(PluginManagerCore.java:710)
	at com.intellij.ide.plugins.PluginManagerCore.loadDescriptors(PluginManagerCore.java:905)
	at com.intellij.ide.plugins.PluginManagerCore.a(PluginManagerCore.java:1064)
	at com.intellij.ide.plugins.PluginManagerCore.initPlugins(PluginManagerCore.java:1256)
	at com.intellij.openapi.application.impl.ApplicationImpl.e(ApplicationImpl.java:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.<init>(ApplicationImpl.java:210)
	at com.intellij.openapi.application.ex.ApplicationManagerEx.createApplication(ApplicationManagerEx.java:45)
	at com.intellij.idea.IdeaApplication.<init>(IdeaApplication.java:112)
	at com.intellij.idea.IdeaUltimateApplication.<init>(IdeaUltimateApplication.java:16)
	at com.intellij.idea.MainImpl$1$1.proceed(MainImpl.java:56)
	at com.intellij.ide.a.g.cb$3.run(cb$3.java:382)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.io.FileNotFoundException: \META-INF\version-notes.xml (系统找不到指定的路径。)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at java.net.URL.openStream(URL.java:1038)
	at com.intellij.util.io.URLUtil.openStream(URLUtil.java:59)
	at com.intellij.util.io.URLUtil.openResourceStream(URLUtil.java:65)
	at com.intellij.openapi.util.JDOMUtil.loadResourceDocument(JDOMUtil.java:376)
	at com.intellij.util.xmlb.JDOMXIncluder.parseRemote(JDOMXIncluder.java:322)
	... 38 more

The plugin was updated by IDEA plugin manager.
It has to **reinstall the plugin**?

**Comment by youyanghuang** [comment] 2016-05-09 02:37
@vsch, it crashes about five times one hour, which makes me crazy.So I have to uninstall it before the next stable version!

**Comment by vsch** [comment] 2016-05-09 09:47
@youyanghuang, sudden crashes are caused by native libraries. Crashes in Java are caught by exception handlers. JavaFX WebView became just barely usable in 1.8.0u40 and has solidified in later releases. The first stable release that I know of is 1.8.0u51, more current releases u60, u66 and u77 are much better choices.

Earlier versions of JavaFX would crash on various image and font files so the issue is also page content dependent.

If it is a JavaFX WebView issue then another release of the plugin will not help. To make sure it is JavaFX you can switch to the Swing Preview browser. If the crashes stop then it is JavaFX and your JRE will need to be upgraded to a more recent release. You can switch preview browser in settings:

![screenshot_settings_previewbrowser](https://cloud.githubusercontent.com/assets/10299086/15109426/5269a9a8-15a9-11e6-85df-5ba47e05feb2.png)

**Comment by youyanghuang** [comment] 2016-05-09 10:43
@vsch  when I switch the preview browser type, it crashes suddenly!
Could you tell me how to debug the plugin or how to find the crash log file?
My files encoding are all utf-8 format!

**Comment by vsch** [comment] 2016-05-09 10:52
@youyanghuang, The log file is under Help menu:

<img width="203" alt="screen shot 2016-05-09 at 6 49 39 am" src="https://cloud.githubusercontent.com/assets/10299086/15111012/6245495a-15b2-11e6-8fcf-027349484b38.png">


If there is an exception trace of the crash can you please send me the part of the log so I can try and figure out what is causing it.

**Comment by youyanghuang** [comment] 2016-05-12 09:49
@vsch  My IDEA IDE was upgraded to the latest version **2016.1.1** on 2016-05-09.
It is very nice that the IDEA never crashes one time until now!!
At last, in the next version, could you will add some features below to the plugin?thanks.

1. markdown files export to pdf or png, jpeg file
2. Auto-scroll markdown-preview editor to match markdown source editor, an enable/disable button can be added to this feature

**Comment by vsch** [comment] 2016-05-12 13:40
@youyanghuang glad to hear the issue is resolved. As I suspected it was probably caused by the old JRE version used by the older IDE.

In the next release I will most likely raise the minimum compatible IDEA version to 15.
