### ISSUE TITLE
#anchor tags not working

### ISSUE THREAD

**Issue by bstout** [vsch/idea-multimarkdown#391] opened 2017-02-25 19:11 UTC
It seems anchor tags in .md docs don't resolve.

Simple case, atop "Inventor.md" is:
[Update] (Inventor.md#patch)

The #patch is red and doesn't resolve.  
![image](https://cloud.githubusercontent.com/assets/742839/23334012/0d484086-fb4b-11e6-9635-7aa191e57dbf.png)

If I reference another .md, and in that .md is an anchor tag, it similarly doesn't resolve and find my anchor tag defined in .md as in:
### <a name="patch"></a> Update

Thanks

**Comment by vsch** [comment] 2017-02-25 19:36
@bstout, HTML is not parsed for anchor tags. Only heading anchors created by GitHub, Jekyll and Kramdown are resolved. The plugin uses the same algorithm (trial and error determined) to create heading ids.

The anchor for a heading with `Update` text is `update` and you do not need to add one manually to have it resolve. You can also use completions to complete all anchors in a file.

These also participate in rename refactoring. So if you invoke "Refactoring -> Rename" on a heading or an anchor referencing it, the changes will be reflected across all anchor references to the heading.

You can add this as a feature request to have HTML anchors available in completions, refactoring and navigation. I have not done it until now because it would require creating a separate PsiElement for HTML anchor tags so these can be full participants in the IDE refactoring.

**Comment by vsch** [comment] 2018-01-06 06:53
@bstout, anchor targets as inline HTML `a` tags with either id or name tag are now implemented.

Need to enable `HTML block deep parsing` (in Languages & Frameworks > Markdown > Parser) if `a` tags are not followed by blank lines or do not have a matching closing tag on the same line.

The first `name` or `id` attribute of the anchor will be taken as the anchor target, the rest (if multiple are present) will be treated as references to the first one if they have the same value. Therefore if you have both id and name with the same value, then renaming one will also rename the other.

EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.

**Closed** 2018-03-16 14:37 UTC
Labels: enhancement, fix available, fixed for next release
