### ISSUE TITLE
Graphviz images not displayed / converted to HTML

### ISSUE THREAD

**Issue by flogy** [vsch/idea-multimarkdown#4] opened 2015-08-25 04:37 UTC
When trying to include a graphviz image, as shown in [this example](https://github.com/TLmaK0/gravizo), it will instead just display the plain text code in the HTML preview and also in the HTML text. This would be very helpful though, as you then could directly generate and include your UML diagrams in your project's documentation.

**Comment by vsch** [comment] 2015-08-25 11:54
I tried it to see where the problem comes from and there is more than one:

1. Used the image url as is: pegdown does not parse the image url and instead spits it out as plain-text. Doable: by fixing pegdown parsing.

2. Used `<img>` tag with the URL encoded version to eliminate any pegdown or plugin processing: The image stream is not accepted as a valid PNG format. It complains deep in the java classes that height and width cannot be \<= 0 and both are 0 at this point in the code. So even if 1. was addressed it still would not load the image from the stream because the PNG image decoder used in the java classes does not like the format.

3. Displayed the image in the browser, saved the resulting file and used markdown image link to see if the final image would be displayed. Yes this worked.

4. Used the GitHub cached image link url to see if it was a problem with streaming vs format. This also displays correctly, so the issue is really the stream content coming back from gravizo.

I don't know what the incompatibility in the java classes since the browser can display the image. I would need to save the raw stream data to a file and compare it to the PNG saved by the browser to figure it out.

I like the feature, but it seems like it will take quite a bit of investigation and coding to have it fixed. This is not a "will not fix", however, I suspect that it will not be trivial and will take some time.

**Comment by vsch** [comment] 2015-09-08 03:30
@flogy, I have some good news for you. The new release which I am probably going to make available today can handle gravizo but not as a Markdown image  but just as a regular HTML `<img` tag.

I implemented a new HTML Preview tab based on JavaFX WebView browser and it handles gravizo images.

Use this format:
```
<img src='http://g.gravizo.com/g?
@startuml;

actor User;
participant "First Class" as A;
participant "Second Class" as B;
participant "Last Class" as C;

User -> A: DoWork;
activate A;

A -> B: Create Request;
activate B;

B -> C: DoWork;
activate C;

C --> B: WorkDone;
destroy C;

B --> A: Request Created;
deactivate B;

A --> User: Done;
deactivate A;

@enduml;
            
'>
```

to get this preview:

<img width="825" alt="screen shot 2015-09-07 at 11 23 29 pm" src="https://cloud.githubusercontent.com/assets/10299086/9725787/84c860d6-55b7-11e5-99ef-e595d5a93b7f.png">

**Comment by flogy** [comment] 2015-09-08 09:59
Awesome! Thank you very much for the fast answer! Keep up the great work!
:+1:

**Comment by vsch** [comment] 2016-01-03 07:40
@flogy, I have some good news for you and some great news!

I hacked multi-line URL images into pegdown and added a cherry on top by adding language injections into the multi-line content. 

![gravizo](https://cloud.githubusercontent.com/assets/10299086/12077689/0664aa3c-b1c0-11e5-9d97-72cf08cee971.gif)

![gravizo2](https://cloud.githubusercontent.com/assets/10299086/12077737/a17e303c-b1c1-11e5-9afa-26bea182f2bf.gif)

I will be finalizing the release tomorrow, so this feature will be in it. 

Customizations for how the text-fragment is converted during fragment editing will be added in the next version. For now removing and adding ; at end of line is hardcoded if the URL starts with "http://g.gravizo.com/g?". 

You can even preview with "PlantUML integration" plugin.

![gravizo3](https://cloud.githubusercontent.com/assets/10299086/12077767/e52368b0-b1c2-11e5-8d28-a364cb36b48d.gif)

Hope you like it.

**Closed** 2016-01-03 07:46 UTC
Labels: enhancement, fixed for next release
