### ISSUE TITLE
Directory linking occasionally broken

### ISSUE THREAD

**Issue by mhaas** [vsch/idea-multimarkdown#623] opened 2018-07-31 12:16 UTC
Linking to directories is occasionally broken. The markdown navigator will show the links in red (as broken) in the editor. The links will work in the JavaFX preview, even though they are also marked as red. If I click a link in the preview, the directory will be selected in the project pane in PyCharm.

I am attaching a screenshot. The main README.md was created by dragging and dropping the files into the editor window from the project pane.

Note that directory linking is not always broken: I have another project where a link to /perl/Test is working fine.

I am using Markdown Navigator  2.5.4.12 in the paid version:

PyCharm 2018.2 (Professional Edition)
Build #PY-182.3684.100, built on July 24, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 3.10.0-862.6.3.el7.x86_64

![image](https://user-images.githubusercontent.com/260872/43458871-091ffd0c-94cc-11e8-89b2-dd989f79d1ff.png)

**Comment by vsch** [comment] 2018-08-06 19:51
@mhaas, the plugin uses the IDE virtual file system for all link resolution. I don't know if linked directories are treated differently than local ones or the plugin is trying to use java File() to test for existence that behaves differently with linked directories.

**Comment by mhaas** [comment] 2018-08-10 06:03
@vsch I may have been unclear in my report: all directories are local, no symbolic links are involved.

**Comment by vsch** [comment] 2018-08-15 13:13
@mhaas, I was able to duplicate this. Directories are only recognized when they are under git vcs roots. 

I fixed this to include directories under the project directory. I will make an EAP release shortly.

Workaround by adding project git vcs, even if nothing is checked in.

**Comment by vsch** [comment] 2018-08-15 19:36
@mhaas, EAP update with a fix for the issue is available.

To enable EAP update channel:

1. Select "Early Access Program" in `Check updates for:`
2. Then make the IDE check for updates.

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

**Closed** 2018-09-17 13:07 UTC
Labels: bug, fix available, fixed for next release
