### ISSUE TITLE
Plugin 'com.vladsch.idea.multimarkdown' failed to initialize and will be disabled

### ISSUE THREAD

**Issue by thomasmodeneis** [vsch/idea-multimarkdown#295] opened 2016-09-09 08:34 UTC
Hi,

I'm getting this error after installing v2016.1.20160405.14

Any ideas ? 
Thanks

```
Plugin 'com.vladsch.idea.multimarkdown' failed to initialize and will be disabled.  Please restart WebStorm.

java.lang.ExceptionInInitializerError
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:249)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:408)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:96)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:455)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:447)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:60)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:361)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: com.intellij.diagnostic.PluginException: com/vladsch/idea/multimarkdown/settings/LicensingStateChanged : Unsupported major.minor version 52.0 [Plugin: com.vladsch.idea.multimarkdown]
    at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:130)
    at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:77)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at com.vladsch.idea.multimarkdown.MultiMarkdownPlugin.<clinit>(MultiMarkdownPlugin.kt:555)
    ... 27 more
Caused by: java.lang.UnsupportedClassVersionError: com/vladsch/idea/multimarkdown/settings/LicensingStateChanged : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:471)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:260)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:256)
    at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:225)
    at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:124)
    ... 31 more
```

**Comment by vsch** [comment] 2016-09-09 16:58
@thomasmodeneis, it looks like an issue with a change in the API. Can you please try the latest patch to see if the issue still exists.

Patch release available from Patch release, EAP update channel or download and install plugin from disk: https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.2.0.0.14.zip

Please let me know if the issue is addressed by the patch release.

**Comment by joshuawhite929** [comment] 2016-11-21 03:17
I get this issue frequently.  It's really painful because IntelliJ will disable the plugin.  Every time I get e-enable it, the same problem occurs.

**Closed** 2016-12-01 12:53 UTC
Labels: bug, cannot reproduce
