### ISSUE TITLE
Mermaid diagram support

### ISSUE THREAD

**Issue by vjpr** [vsch/idea-multimarkdown#472] opened 2017-07-24 10:35 UTC
I currently use `markdown-preview-enhanced` for Atom, but I would love to migrate all my markdown editing to IntelliJ.

It supports:

- Math rendering- KaTeX, MathJax
- Reveal.js presentations
- Mermaid diagrams - http://knsv.github.io/mermaid/#mermaid

Is there a way that this plugin could easily support extensions like Mermaid?

I'm guessing playing with `HTML Generation` might work?

**Comment by vjpr** [comment] 2017-07-24 10:49
Okay so using the `HTML Generation` options I can get it to work with the Swing renderer. But Mermaid doesn't work with the JavaFX renderer.

**Comment by vsch** [comment] 2017-07-25 01:28
@vjpr, it is a conflict between HighlightJS and mermaid. Make sure highlight js and prism are not selected. HighlightJS does syntax highlighting of `<pre><code>` blocks.

![image](https://user-images.githubusercontent.com/10299086/28551585-dcfe8930-70b6-11e7-8878-f5c8f7f672e4.png)

**Comment by fazleskhan** [comment] 2018-05-17 16:30
@vjpr I am trying to render a mermaid sequence diagram with a trial licensed plugin and am having trouble getting it to work. Could you provide a how-to on getting it to work?

**Comment by vsch** [comment] 2018-05-17 16:54
@fazleskhan, you need to add the mermaid scripts to the HTML generated page.

The following markdown will render correctly in JavaFX preview. Swing has no JavaScript so it will not work in Swing.

```markdown
<script src="https://unpkg.com/mermaid@8.0.0-rc.8/dist/mermaid.min.js"></script>
<script>mermaid.initialize({startOnLoad:true});</script>

<div class='mermaid'>
sequenceDiagram
    participant Alice
    participant Bob
    Alice->John: Hello John, how are you?
    loop Healthcheck
        John->John: Fight against hypochondria
    end
    Note right of John: Rational thoughts <br/>prevail...
    John-->Alice: Great!
    John->Bob: How about you?
    Bob-->John: Jolly good!
</div>
``` 

Screenshot of preview:

<img width="566" alt="image" src="https://user-images.githubusercontent.com/10299086/40192009-269adf7c-59d1-11e8-8c82-584b0462ba85.png">

The two script tags should be added to settings HTML Generation to be inserted into all HTML pages instead of markdown documents:

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/10299086/40192104-65db113e-59d1-11e8-83c3-e662bbc2bc1a.png">

**Comment by vsch** [comment] 2018-05-17 16:56
@fazleskhan, @vjpr, it will not work with fenced code because the tags are wrong for mermaid. You have to use `<div class="mermaid">`

**Comment by fazleskhan** [comment] 2018-05-17 18:04
@vjpr 
thanks! 

@vsch 
fenced tags worked for me  

```
```mermaid
sequenceDiagram
    participant Alice
    participant Bob
    Alice->John: Hello John, how are you?
    loop Healthcheck
        John->John: Fight against hypochondria
    end
    Note right of John: Rational thoughts <br/>prevail...
    John-->Alice: Great!
    John->Bob: How about you?
    Bob-->John: Jolly good!
 ```
```
![fencedtagsworking](https://user-images.githubusercontent.com/6166145/40195312-2ce863f4-59db-11e8-935c-cd28fc915b4f.PNG)

**Comment by vsch** [comment] 2018-05-17 18:10
@fazleskhan, thank you for the info. After your success I was motivated to figure out that HighlightJS conflicts with mermaid. Disabling HighlightJS allows mermaid to be used with fenced code.

**Comment by stefan2** [comment] 2018-06-19 13:09
As a quick fix

Settings |  `Head Bottom`

```
// JavaFX needs basic JS
<script>
    // using prism
    var mermaids = document.getElementsByClassName('language-mermaid');
    while(mermaids.length > 0) {
        mermaids[0].className = 'mermaid';
    }
    
    // using highlight
    var mermaids = [];
    [].push.apply(mermaids, document.getElementsByClassName('mermaid'));
    for (i = 0; i < mermaids.length; i++) {
        mermaids[i].className = 'nohighlight mermaid';
    }
</script>
<script src="file:/A:/cache/mermaid.min.js"></script>
<script>mermaid.initialize({startOnLoad:true});</script>`
```
The issue with prism is, that you add the `language-` prefix on classes, but mermaid require the static class `mermaid`.


The issue with highlight is, that hljs render the codeblock first, so mermaid run into errors.

```
flow.js:314 Uncaught Error: Parse error on line 1:
graph <span class="hljs-bui
```
To prevent this, the class `nohighlight` is required.

The components are execute `onload`, which can lead to issues. But codeblock rendering is cool, so more control would be really great.

For example:

- new option: "don't insert scripts"

If yes, no scripts are added to the HTML-Output. Now you can do your tricks in `Head Bottom`.

```
// path to existing local scripts …? 
var markdownNavigatorScripts = {
  'highlight': '/tmp/multimarkdown_highlight.pack.js',
  'prism': '/tmp/multimarkdown_prism.pack.js',
  '…': '…'
}

1. load (from remote)mermaid
2. mermaid.render(elements)
3. load (from local)highlight
4. highlight.render(elements)
```

Same approach with CSS (using a style you want. see downloads on prismjs)

**Comment by vsch** [comment] 2018-06-19 23:14
@stefan2, thank you for posting this workaround. 

I think it will be easier if I add mermaid as one of the stylesheet scripts along with highlightjs and prism then the intricacies and interactions can be addressed in the code automatically.

**Comment by stefan2** [comment] 2018-06-20 11:37
Sounds good, but don't forget the fabulous "Other". You know, there are lots of pros and cons for both :-)  ... Or different renderers at the same time. The topic "different renderers" could become a bit more complex. 

Example: I want prism and "flowchartsjs" instead of mermaid because flowchartjs is supported by my favorite doc generator. The same hack (as above) works, but is a dirty solution.

**Comment by vsch** [comment] 2018-08-31 01:59
@vjpr, @fazleskhan, @stefan2, I added  [GitLab Flavoured Markdown](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/user/markdown.md)
  parsing and rendering functionality
  * Math inline using ```$``$``` and fenced code blocks with info of `math` using
    [Katex](https://github.com/Khan/KaTeX)
  * Charts fenced code blocks with info of `mermaid` using
    [Mermaid](https://github.com/knsv/mermaid)
  * Ins/Del via `{++}` and `[++]`/`{--}` and `[--]`
  * Multi-line block quotes
  * Video image link rendering

This only applies to parsing and rendering HTML not the style sheet. Also link completions are GitHub like. The latter is for release 3.0.

EAP update with a fix for the issue is available.

To enable EAP update channel:

1. Select "Early Access Program" in `Check updates for:`
2. Then make the IDE check for updates.

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

**Comment by vsch** [comment] 2018-08-31 09:59
@stefan2, I forgot to mention that you need to enable the GitLab parser option and Fenced Code for math and mermaid blocks. It works with prism and HighlightJS.

<img width="974" alt="screen shot 2018-08-31 at 5 56 35 am" src="https://user-images.githubusercontent.com/10299086/44906459-f2269000-ace2-11e8-98f2-add238b0ec56.png">



<img width="963" alt="image" src="https://user-images.githubusercontent.com/10299086/44906330-90662600-ace2-11e8-9fa8-99b823ffde4a.png">

**Comment by stefan2** [comment] 2018-08-31 10:37
https://www.youtube.com/watch?v=F-nuV36fvgQ

Thank you!

**Closed** 2018-09-17 13:07 UTC
Labels: enhancement, fix available, fixed for next release

**Comment by vjpr** [comment] 2020-03-01 16:05
I can't get it working anymore. Do I need to include a stylesheet? Has anything changed recently that would prevent it working. I have enabled GFM and code fences.

**Comment by vsch** [comment] 2020-03-26 17:23
@vjpr, you also have to enable either GitLab extensions or just mermaid or math extensions.

**Comment by HZ89** [comment] 2020-05-12 02:42
mermaid not working in swing.

**Comment by vsch** [comment] 2020-05-12 18:43
@HZ89, mermaid rendering is done by an in-page JavaScript. Swing does not support JS so will not display mermaid diagrams.

In EAP release of the plugin, Kroki.io was added as an option for rendering some fenced code content, including mermaid.

If you upgrade to the EAP plugin (or wait for the next official release) you will be able to configure fenced code rendering to use Kroki.io for mermaid, in which case they will display in Swing.

<img width="1103" alt="image" src="https://user-images.githubusercontent.com/10299086/81732789-f9fa7980-945e-11ea-864f-db8000efc4d7.png">


EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)

Please note the change that EAP channel is for JetBrains licensed plugin and Legacy EAP is for legacy licensing by vladsch.com
