### ISSUE TITLE
Add support for rendering a svg image

### ISSUE THREAD

**Issue by josefglatz** [vsch/idea-multimarkdown#572] opened 2018-03-19 18:41 UTC

**Comment by josefglatz** [comment] 2018-03-19 19:01
Thank you for your quick reply! I really like your plugin!

Ok, so I have to investigate further – PhpStorm crashes whenever I try to activate JavaFX preview browser. Do you have maybe any hint where I can debug this behaviour?

I'm using macOS HighSierra with latest PhpStorm EAP (licensed) and your plugin (licensed)

**Comment by vsch** [comment] 2018-03-19 19:14
@josefglatz, I am running latest EAP but not non High Sierra. Under parallels running High Sierra I was only able to run with JavaFX by using the Oracle JRE for the IDE, in this case IntelliJ IDEA but the code under the hood is the same.

I suspect there is an issue with the bundled JDK in the IDE with high sierra.

Install Oracle latest JDK (8u162 I think.

Change the boot JDK hold down left Shift and press and hold the Options and Cmd keys, then press the / key. You should get the boot jdk switch option. Select the oracle JDK.

I really do not recommend the Oracle JDK because it has inferior text rendering but in this case it is either crash or have less than optimum text rendering.

If this solves your issue then you should report it to JetBrains so they can fix it.

I would report it but being a plugin developer, I get the feeling that my reports go to the bottom of the stack.

**Comment by vsch** [comment] 2018-08-30 02:04
@josefglatz, btw JavaFX preview for High Sierra was fixed in 2.5.4 but you are better off getting the latest EAP. It has a few more bug fixes and new features.

To enable EAP update channel:

1. Select "Early Access Program" in `Check updates for:`
2. Then make the IDE check for updates.

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

**Closed by vsch** 2018-08-30 02:04 UTC

**Comment by vsch** [comment] 2018-12-18 03:36
@josefglatz, SVG support added to swing preview browser. 

EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)
