### ISSUE TITLE
Export to PDF greyed out

### ISSUE THREAD

**Issue by jimlongo56** [vsch/idea-multimarkdown#544] opened 2018-01-02 23:15 UTC
Hi,

I can't tell what the error is.  Both the Toolbar item and Tools>Markdown Navigator>Export rendered Markdown to PDF are greyed out and unavailable.

![screen shot 2018-01-02 at 6 12 17 pm](https://user-images.githubusercontent.com/6787988/34503835-aa1ece60-efe8-11e7-8fb6-f637da39f731.png)

What steps do I need to take to enable Export to PDF.

**Comment by vsch** [comment] 2018-01-02 23:19
@jimlongo56, can you post a snapshot with the full tooltip. The part after disabled by: is cut off so I cannot see what caused it to be disabled.

**Comment by jimlongo56** [comment] 2018-01-02 23:19
That's the way it looks on my screen, cutoff.

**Comment by vsch** [comment] 2018-01-02 23:23
@jimlongo56, that explains it. That appears to be an issue in the IDE. What IDE, Version and OS are you running?

The plugin does not handle the rendering or clipping of the tooltip. I will try to duplicate this because on my dev system it always displays the full multiline tooltip.

**Comment by jimlongo56** [comment] 2018-01-02 23:25
PhpStorm 2017.3.2
Build #PS-173.4127.29, built on December 22, 2017
Subscription is active until February 20, 2018
JRE: 1.8.0_152-release-1024-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.2

**Comment by vsch** [comment] 2018-01-03 00:27
@jimlongo56, I suspect it is the OS X High Sierra version. I am going to try and upgrade my parallels copy of OS X 10.12.6.

To make sure it is the OS can you try seeing a tooltip on the IDE:

<img width="247" alt="screen shot 2018-01-02 at 7 24 24 pm" src="https://user-images.githubusercontent.com/10299086/34505356-bf7a291c-eff2-11e7-83fa-cbeaf5e25f60.png">

**Comment by jimlongo56** [comment] 2018-01-03 02:26
I get the same result on my laptop
PhpStorm 2017.3.2
Build #PS-173.4127.29, built on December 22, 2017
Subscription is active until February 20, 2018
JRE: 1.8.0_152-release-1024-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.2


Here's what I get on that tooltip

![screen shot 2018-01-02 at 21 16 10](https://user-images.githubusercontent.com/6787988/34507310-b3974fe8-f002-11e7-8daa-22bf8fb1da03.png)

**Comment by vsch** [comment] 2018-01-03 03:34
@jimlongo56, found how to duplicate it. If the toolbar is collapsed then the tooltips are clipped to its area when it is popped out. Not something the plugin can control.

Can you temporarily make the editor window big enough to show the toolbar so the full pop-up can be visible?

From the truncated message it looks like something is null that is not supposed to be but it is a guess.

**Comment by jimlongo56** [comment] 2018-01-03 03:43
![screen shot 2018-01-02 at 10 43 34 pm](https://user-images.githubusercontent.com/6787988/34508528-677941c8-f00e-11e7-8693-f6a48ebfa0eb.png)

**Comment by vsch** [comment] 2018-01-03 12:00
@jimlongo56, the button is disabled because you have preview only mode selected.

The toolbar button needs the current editor in order to determine the context of text, selection and carets for the button action.

In this case the editor is not shown so the toolbar button cannot find an editor on which to operate.

I will see if I can find the editor from the preview pane but for now switch to text only or text and preview and the button will be enabled.

**Comment by vsch** [comment] 2018-01-03 13:49
@jimlongo56, fixed in latest EAP build. Also improved the message to say that editor is not showing instead of null.

EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.

**Comment by jimlongo56** [comment] 2018-01-04 18:12
Thank you.

**Closed** 2018-03-16 14:36 UTC
Labels: bug, enhancement, fix available, fixed for next release
