### ISSUE TITLE
Markdown preview is lagging

### ISSUE THREAD

**Issue by kiru** [vsch/idea-multimarkdown#569] opened 2018-03-16 10:14 UTC
Hello @vsch , 

We're using gravizo for creating diagrams. 
Having few diagrams and text in the same files seems to slow the parsing down. 

I'm not sure if that is just the case for gravizo links, in general for having many images. 
Here is a test file: https://gist.github.com/kiru/8fd7a83c83a5c514f31885b21143e98d

I also see a few glitches like these: 

![image](https://user-images.githubusercontent.com/2451608/37515428-09048ec8-290b-11e8-8c95-077b7a1fd4a6.png)

Thank you, 
Kiru

**Comment by vsch** [comment] 2018-03-16 12:41
@kiru, the slow down is a JavaFX WebView issue caused by its image display. I have noticed that typing with preview enabled when the file contains a lot of images is practically impossible because JavaFX WebView update blocks the AWT thread which is used for all UI processing in the IDE.

The update glitch is also a JavaFX WebView issue. It also happens if you resize the preview vertically. WebView seems to get confused and the only way to correct it is to re-create a new WebView instance by closing the preview, and sometimes the editor.

Addressing typing delay with preview open is planned for version 2.6.0. Release 2.5.0 is ready and I am debating whether to release it today or give it another couple of days to see if any show stopper bugs are discovered.

After this release I have a few major efforts planned, one of which is seeing if I can implement incremental preview update to eliminate the typing delay in large files or ones with a lot of images in them.

**Comment by kiru** [comment] 2018-03-16 13:05
Thank you for the quick and thorough reply. The planned changes sound really promising.

**Comment by tjakobsson** [comment] 2018-05-24 08:42
I'm using GoLand and while editing a medium large markdown file with images. It goes to the point when the whole IDE becomes almost totally unresponsive. It's not instantly slow, it becomes slow after a few words of editing. I guess this is the same reason, with JavaFX WebView? If not, I'll add a new issue. But it "feels" like this is the same issue.

**Comment by vsch** [comment] 2018-05-24 13:52
@tjakobsson, it could also be a potential memory leak which I am trying to duplicate to figure out if it is something the plugin is causing or if it occurs in JavaFX WebView. #579

**Comment by vsch** [comment] 2018-11-29 05:12
I found a bug and a couple of performance issues not just with images but links in general. 

The image caching issue is still part of JavaFX WebView but at least the typing is without lagging. 

If you touch type and don't like any delay then I recommend setting the typing delay to 250 ms, which will allow you to type at full speed and update the preview on a slight pause.

![image](https://user-images.githubusercontent.com/10299086/49200495-1ab63880-f36b-11e8-8e0f-51a562d30bde.png)

HTML rendering for preview sped up by 7x-8x, link resolution by 5x or more. Overall, I can type again in large files containing lots of images and links with the preview on.

EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)

**Comment by vsch** [comment] 2019-03-01 18:28
@tjakobsson. I think this one is finally fixed for next release. #710 brought to my attention the message bus registration which I completely missed as an external reference to the instance which would keep it alive for the life of the project.

Fixed for next release along with other bad old bugs and performance issues. I will post when an EAP with the fix will be available.

**Comment by vsch** [comment] 2019-03-09 04:13
EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)

**Closed** 2019-03-30 22:21 UTC
Labels: bug, fix available, fixed :), fixed for next release
