### ISSUE TITLE
Using tab to move to the next table cel. 

### ISSUE THREAD

**Issue by jorisrietveld** [vsch/idea-multimarkdown#541] opened 2017-12-15 05:21 UTC
Hi, first of all I want thank you for putting in the effort by creating this plugin. It really helped to reduce the time I wasted by creating tables. (They just have to be perfectly aligned...). But I have a question, I tried to find a way to configure the tab key so that it moves to the next cell when I am editing a table but I could not figure it out. I tried several things with the key map, live templates and looked through the settings of the plugin. Do you know a way to configure this behavior or is this just not possible at the moment? Thanks in advice!

**Comment by vsch** [comment] 2017-12-16 19:17
@jorisrietveld, thank you for your support.

This is on a todo list. 

The IDE implementation does not really expect standard keys like TAB, ENTER, SPACE, etc to be re-mapped to non-standard actions.

To make it work properly I have to intercept the tab key in Markdown editor and map it an action based on context and also take care of all the pop-up states. Otherwise, the key will work for navigation and list indenting but will stop working for completions or other pop-ups.

**Comment by vsch** [comment] 2017-12-16 19:19
Duplicate of #469

**Comment by vsch** [comment] 2018-08-29 22:54
@jorisrietveld, I finally got this working for both tables and lists. Main settings for plugin has tab override options, enabled by default.

<img width="1036" alt="screen shot 2018-08-29 at 6 53 31 pm" src="https://user-images.githubusercontent.com/10299086/44819976-ee005280-abbc-11e8-89b5-5c4bbaeb4b5a.png">

EAP update with a fix for the issue is available.

To enable EAP update channel:

1. Select "Early Access Program" in `Check updates for:`
2. Then make the IDE check for updates.

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

**Closed** 2018-09-17 13:07 UTC
Labels: duplicate, enhancement, fix available, fixed for next release
