### ISSUE TITLE
Export .html files (as part of build?)

### ISSUE THREAD

**Issue by jimpudar** [vsch/idea-multimarkdown#314] opened 2016-10-12 17:41 UTC
I have a Java project and am planning on using your plugin to facilitate creation of documentation. We unfortunately can not use GitHub or any other online service which renders `.md` files to view them, so we want to use your plugin to generate the HTML with CSS. My folder structure looks like this:

``` text
.
├── app.iml
├── doc
│   ├── ex1.md
│   ├── ex2.md
│   ├── ex3.md
│   ├── ...
│   └── README.md
├── pom.xml
├── src
│   └── main
└── target
     ├── app-SNAPSHOT.jar
     ├── app-SNAPSHOT-jar-with-dependencies.jar
     ├── archive-tmp
     ├── classes
     ├── generated-sources
     ├── maven-archiver
     ├── maven-status
     ├── surefire
     └── doc
         ├── ex1.html
         ├── ex2.html
         ├── ex3.html
         ├── ...
         └── README.html
```

I would like to be able to (ideally as part of my Maven build) automatically generate `.html` files in my `target/doc` folder for all the `.md` files in the `doc` folder.

As you have suggested [here](https://github.com/vsch/idea-multimarkdown/issues/51), I have simply been copying and pasting the `HTML` into the `target/doc` folder manually. 

However, we have the rest of my team will also be frequently working on these `.md` files and I really need an easy way to rebuild all the corresponding `HTML` files. Spending hours a day to copy and paste `HTML` is not really an option for us. 

We really, really need an "Export HTML" feature! 

Also, let me take a second to say thanks for an AWESOME plugin, which I have immediately found indispensable.

**Comment by vsch** [comment] 2016-10-12 20:10
@jimpudar, the quickest implementation I could propose would be to have an export action with the following export configuration options:

1. Source and target directories. The directory structure under the source directory would be duplicated under the target directory.

2. CSS and JS Script target directories that will contain the CSS and JS files used in each HTML document, with an button to update the files in these directories from the internal ones. This way the files are updated when the button is clicked but thereafter you can manually edit these in case you want them to differ from the ones used for preview.

3. Have an option to update generated HTML files when Markdown files are saved.

Will this be sufficient for your project requirements?

**Comment by jimpudar** [comment] 2016-10-12 20:11
Absolutely. This would be incredibly helpful! Thanks a lot for your quick
response.

**Comment by vsch** [comment] 2016-10-12 20:14
@jimpudar, you are welcome.

I will update the issue with a patch release with the added feature. With your help we can polish the functionality once the foundation functionality is implemented and you get to try it out on your project.

**Comment by vsch** [comment] 2016-10-14 02:19
@jimpudar, this feature required implementing project specific Markdown settings. It was on the todo list but I procrastinated on it until I had no choice. Global Markdown settings were passable until I started adding HTML Export, which is very much project dependent.

This is now done so I can proceed to the actual export functionality.

As an added bonus the new version will have Preview, Parser, Style Sheet, HTML Generation and HTML Export as project settings.

**Comment by vsch** [comment] 2016-10-20 02:38
@jimpudar, Interim implementation will have the features as outlined above. Early implementation is scheduled to be released in a couple of days to give you a working solution.

The final implementation will have scope based rendering profiles to allow scope based control of all rendering and html export features. This way with a bit of configuration it will be possible to control preview and html export as fine grained as desired.

**Comment by vsch** [comment] 2016-10-21 03:17
@jimpudar, early working version available for download: https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.2.1.1.6.zip

1. Parent Dir should contain the top directory from which you want to export Markdown to HTML files
2. Target Dir should contain the directory where HTML is to be exported, relative path of file to parent dir is preserved here.
3. Target Ext if selected then text box content will be used as the extension, include a period or the text will be appended to the file name. Otherwise ".html" will be used.
4. Export HTML on save needs to be selected if you want files to be exported when you save.
4. Plain HTML if selected then the exported HTML will be like the unmodified HTML view, otherwise HTML Text view
5. No Stylesheets, No Scripts can be used to prevent exported HTML from having links to scripts and stylesheets. Otherwise scripts and stylesheets will be exported to CSS and Script dir respectively. These files will only be exported if they don't already exist.

The Insert Macros button can be used to insert macros. If some don't work as expected please let me know.

Some caveats:

❗️After you setup the HTML export parameters the files will be exported when a file is modified. To export all applicable files use the main menu: Tools > Export Markdown as HTML <img width="281" alt="screen shot 2016-10-20 at 11 12 18 pm" src="https://cloud.githubusercontent.com/assets/10299086/19585474/bb17ddf6-971a-11e6-90ef-7ba9d816ab6f.png">. 

After that, every time you save a modified markdown file that is part of the export config, the HTML will be automatically exported.

Exported files are not deleted if you turn off export or change the config. You will need to delete them manually.

<img width="961" alt="screen shot 2016-10-20 at 10 16 56 pm" src="https://cloud.githubusercontent.com/assets/10299086/19585183/425fda82-9718-11e6-9ee8-007a7fcc49f2.png">

**Comment by vsch** [comment] 2016-10-26 13:13
Scope based rendering profiles Implementation in 2.1.1.8 or later, update available in EAP plugin channel.

**Comment by bstout** [comment] 2016-10-26 17:19
Another feature I'd like to add on here (cross posted from #317):

I was thinking if I distribute HTML files as documentation, whereby all links need to be relative/local.  Then these HTML files could serve as documentation and I used the same markdown tool to generate them as the github docs.

**Comment by vsch** [comment] 2016-10-26 17:27
@bstout , It is a good idea. I will add the option to HTML Export config to generate relative links in exported files whose targets are also exported. The relative link will be based on the relative exported location between the source and target.

It will probably be quite a churn of the HTML generation code but the feature makes a lot of sense as far as HTML Export is concerned to create stand-alone HTML docs.

As far as the links to non-exported files, the absolute link to the GitHub file location will remain.

I am also adding options to copy linked image files to an image directory. Links to these images will also be relative from source file to image file.

If image files are not copied then the links will be to their GitHub link as in preview. If files are copied then to address possibility of duplicated image file names I am adding two options:

1. Add numeric sequence to make files unique. For example two files named image.png will be mapped to: 
    * first file changed to imageDir/image.png
    * second file changed to imageDir/image_1.png
2. Use path relative to project directory. This will replicate image file path from project directory under the imageDir.
   
Does this make sense?

**Comment by bstout** [comment] 2016-10-26 17:36
@vsch The additional logic for duplicate images seems complicated, and I'm not sure I understand the need.  If there's an export dir like "local_resources", then an HTML page with a link with say "<server>/img/x/foo.gif" could be put the "local_resources" dir as local_resources/img/x/foo.gif

Then, the path to this in the img link could be relative based on the current HTML and location of this configured local_resources dir.

Again, I'm not sure I'm getting all the issues - but this is my stab at it.

**Comment by vsch** [comment] 2016-10-26 20:20
@bstout, if you select the "Path relative to project" option which will give you what you describe.

If you want a simpler, flat image directory then adding a numeric suffix would be a better option. Preferably there are no name collisions but if there are then this option will work. Not perfect since to get the image file name right all exportable files have to be exported. Otherwise, adding an image reference somewhere can affect an already exported file.

I am making the project relative path the default. I will leave the other option in as "Your mileage may vary". I can see on projects where file name uniqueness can be guaranteed and it may be a desired export option.

**Comment by vsch** [comment] 2016-10-27 00:31
@bstout, I reviewed the numeric sequence option and decided it was not viable because it would prevent the ability to export one file at a time because the image file names were not deterministic.

The option was changed to "Add file name only" without concern for duplicates. In the case of duplicate file names the image file with the most recent modification time will be copied. This option is only to be used in cases where a flat image directory is desired and duplicate files are not an issue.

**Comment by vsch** [comment] 2016-10-27 04:23
@bstout, @jimpudar, image copying and links to exported HTML files implemented in 2.1.1.10 or later, update available in EAP plugin channel.

[HTML Export wiki](https://github.com/vsch/idea-multimarkdown/wiki/HTML-Export) updated.

All feedback is appreciated.

![](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/Screenshot_HtmlExport.png)

**Comment by bstout** [comment] 2016-10-27 20:13
@vsch I probably don't have something correct.
I have a README.md page with:
[User Management ](user.md)

In the same dir, I have a user.md file.

the generated HTML includes a full link address that references github.  My hope was the HTML would similarly use a relative URL as I did in the mardown link

**Comment by vsch** [comment] 2016-10-27 20:22
@bstout, relative links will only be used to files that are also exportable.

You need to have the "Export HTML on save" and "Lint to exported HTML" selected for the profile in question.

Both README.md and user.md should be exportable in some rendering profile. When you invoke the "Export Markdown as HTML" in the tools menu do you have both files exported as HTML?

**Comment by bstout** [comment] 2016-10-27 20:28
@vsch Yes both files are exported as HTML and it's in clicking the link in the README html file that I see the link clicks to github instead of link to a relative file.

Both checkboxes are also checked for export on save and link to exported.

The link comes out as: `<p><a href="https://--edited--/blob/master/docs/api/user.md">User Management </a></p>`

**Comment by vsch** [comment] 2016-10-27 20:31
@bstout, are you running on Windows? The handling of paths could be messed up for Windows.

**Comment by bstout** [comment] 2016-10-27 20:32
@vsch No, OSX 10.12.1

**Comment by vsch** [comment] 2016-10-27 20:36
@bstout, Can you give a screenshot of your HTML Export settings?

I want to double check the directory settings.

**Comment by bstout** [comment] 2016-10-27 20:43
@vsch 
![image](https://cloud.githubusercontent.com/assets/742839/19784637/5d4c8812-9c4b-11e6-9623-a390002efa09.png)

**Comment by vsch** [comment] 2016-10-27 20:52
@bstout, are you using JavaFX WebView preview or Swing? 

Need validate that I correctly implemented all the features across all the options.

**Comment by bstout** [comment] 2016-10-27 20:54
@vsch no problem
![image](https://cloud.githubusercontent.com/assets/742839/19785069/e8a0d89a-9c4c-11e6-89c1-e1d329f528ce.png)

**Comment by vsch** [comment] 2016-10-27 21:28
@bstout, thank you for the info. I am now able to duplicate this with some test files. Will post fix.

**Comment by vsch** [comment] 2016-10-27 21:49
@bstout, fixed. Relative links would only work if there were copied image files. Over-ambitious optimization.

EAP channel updated with version 2.1.1.14 with the fix.

**Comment by bstout** [comment] 2016-10-27 21:50
@vsch sweet!

**Comment by vsch** [comment] 2016-10-27 22:12
@bstout could be something else. As a test can you download this zip: https://github.com/vsch/idea-multimarkdown/raw/master/export.zip

It has an export directory with 2 markdown files and also an image directory and an out directory with results of export on my dev system.

If you setup HTML export as you do for your other files and see if this exports correctly. The export/out directory contains the exported files on my system, with all links relative.

I want to make sure that we have the same behaviour on known inputs.

**Comment by vsch** [comment] 2016-10-27 23:02
@bstout, just duplicated the issue under different conditions. No relative links are generated if the source directory is not under VCS. Will see what is causing it.

**Comment by vsch** [comment] 2016-10-27 23:09
@bstout, found the cause. VCS was not the cause. Another condition was causing it to skip relative link generation. Will make a new fix with this issue and also add relative links for style sheets and scripts.

**Comment by vsch** [comment] 2016-10-28 02:46
@bstout, fixed. Now relative links work consistently even if files or images are not under VCS.

EAP channel updated with version 2.1.1.16 with the fix.

Now exporting will create all the necessary files and use relative links to them: css, js and custom font file used for JavaFX WebView. Opening the html in browser should result in what you see in the preview if not using "No Stylesheets, No Scripts" option.

I did mention there was going to be a lot of code churn to support this feature. Glad I did it thanks to the motivation from both of you: @bstout and @jimpudar.

**Comment by bstout** [comment] 2016-10-28 02:51
@vsch Confirmed - works beautiful.

**Comment by vsch** [comment] 2016-10-28 02:52
@bstout, that was a fast confirmation. Thank you.

**Comment by vsch** [comment] 2016-11-04 20:52
Please see #330 for update to HTML export functionality with auto export on save, settings change and project open.

**Closed** 2016-12-01 12:52 UTC
Labels: enhancement, fix available, fixed for next release
