### ISSUE TITLE
Error while indexing ..\node_modules\webpack-stream\node_modules\node-libs-browser\README.md

### ISSUE THREAD

**Issue by eliagrady** [vsch/idea-multimarkdown#250] opened 2016-06-08 07:35 UTC
This is the call stack:
Error while indexing C:\dev\modules\boily\node_modules\webpack-stream\node_modules\node-libs-browser\README.md
To reindex this file IDEA has to be restarted: 3373
java.lang.ArrayIndexOutOfBoundsException: 3373
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.visit(LexParserASTVisitor.java:1482)
	at org.pegdown.ast.TableBodyNode.accept(TableBodyNode.java:25)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.visitChildren(LexParserASTVisitor.java:1911)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.addChildTokens(LexParserASTVisitor.java:2021)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.addCompositeTokensWithChildren(LexParserASTVisitor.java:1946)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.addCompositeTokensWithChildren(LexParserASTVisitor.java:1937)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.visit(LexParserASTVisitor.java:1475)
	at org.pegdown.ast.TableNode.accept(TableNode.java:63)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.visitChildren(LexParserASTVisitor.java:1911)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.visitChildren(LexParserASTVisitor.java:1844)
	at com.vladsch.idea.multimarkdown.parser.LexParserASTVisitor.visit(LexParserASTVisitor.java:388)
	at org.pegdown.ast.RootNode.accept(RootNode.java:100)
	at com.vladsch.idea.multimarkdown.parser.MultiMarkdownLexParser.parseMarkdown(MultiMarkdownLexParser.java:55)
	at com.vladsch.idea.multimarkdown.parser.MultiMarkdownLexParserManager.parseMarkdown(MultiMarkdownLexParserManager.java:174)
	at com.vladsch.idea.multimarkdown.parser.MultiMarkdownLexer.start(MultiMarkdownLexer.java:95)
	at com.intellij.lexer.Lexer.start(Lexer.java:47)
	at com.intellij.lang.cacheBuilder.DefaultWordsScanner.processWords(DefaultWordsScanner.java:70)
	at com.intellij.psi.impl.cache.impl.id.IdTableBuilding$WordsScannerFileTypeIdIndexerAdapter.map(IdTableBuilding.java:119)
	at com.intellij.psi.impl.cache.impl.id.IdTableBuilding$WordsScannerFileTypeIdIndexerAdapter.map(IdTableBuilding.java:106)
	at com.intellij.psi.impl.cache.impl.id.IdIndex$4.map(IdIndex.java:85)
	at com.intellij.psi.impl.cache.impl.id.IdIndex$4.map(IdIndex.java:79)
	at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:398)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1831)
	at com.intellij.util.indexing.FileBasedIndexImpl$23.run(FileBasedIndexImpl.java:1760)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:510)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1718)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1703)
	at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:108)
	at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:105)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$1.run(CacheUpdateRunner.java:226)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$2.run(CacheUpdateRunner.java:246)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:240)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Might be a problem with a dependency?

**Comment by atyapin** [comment] 2016-06-08 09:27
It seems to be a duplicate of [#247](https://github.com/vsch/idea-multimarkdown/issues/247)
1.7.0.5 helped me to avoid the error but I cannot see dependencies 
`[![dependencies status](http://david-dm.org/webpack/node-libs-browser.png)](http://david-dm.org/webpack/node-libs-browser)` in `node-libs-browser\README.md` after installing the patch.

**Comment by vsch** [comment] 2016-06-08 13:38
@eliagrady, the bug is indeed resolved in 1.7.0.5, https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.7.0.5.zip

**Comment by vsch** [comment] 2016-06-08 13:39
@atyapin, I tried the link you have trouble with and it seems to work. Can you please post a screenshot of what your preview looks like so I can try and resolve the issue.

<img width="961" alt="screen shot 2016-06-08 at 9 36 17 am" src="https://cloud.githubusercontent.com/assets/10299086/15896129/e5b5366c-2d5c-11e6-9f27-beabad624047.png">

**Comment by atyapin** [comment] 2016-06-08 13:50
![image](https://cloud.githubusercontent.com/assets/16883882/15896461/2301e40c-2d99-11e6-8d0c-d1cc6d8aed06.png)

**Comment by vsch** [comment] 2016-06-08 13:54
@atyapin, you are using Swing preview which does not support SVG graphics. Is there a reason why you are not using the JavaFX preview?

![screenshot_settings_previewbrowser](https://cloud.githubusercontent.com/assets/10299086/15896607/f7909014-2d5e-11e6-9dad-285c88951e51.png)

**Comment by atyapin** [comment] 2016-06-08 14:16
Thanks a lot, it works now.

**Closed** 2016-06-14 16:17 UTC
Labels: duplicate, fix available, fixed for next release, ☹ bug
