### ISSUE TITLE
Image pasting under ubuntu cinnamon

### ISSUE THREAD

**Issue by wotanii** [vsch/idea-multimarkdown#458] opened 2017-06-27 15:25 UTC
#### Problem
Pasting images from clipboard doesn't work under ubuntu/cinnamon. 

#### Reproduction
1. Safe screenshot to clipboard (default: ctrl + print) 
1. paste into MD-Editor (default ctrl + v)
1. paste into pinta (or any other image editor) to check if the image was actually copied

##### Result
1. in MD-Editor nothing happens
1. in pinta Screenshot appears

##### Expected Result
screenshot appears in MD Editor

#### Workaround
Safe screenshot to file, then Drag&Drop it into MD-Editor to insert full file path, then write out markdown by hand to include image. 

#### System
ubuntu 16.10 + cinnamon 3.0.7 

pycharm 2017.1.4 + Markdown Navigator 2.3.7

#### Related Observations: 

* Drag & Drop from Nemo (file-manager) into md-editor --> inserts full file path (e.g. "/home/juergens/Bilder/Bildschirmfoto vom 2017-06-02 15-37-42.png" )
* Copy in Nemo, paste into md-editor --> inserts full file path without protocol (e.g. "/home/juergens/Bilder/Bildschirmfoto vom 2017-06-02 15-37-42.png")
* Copy images from pycham's project view and paste into editor --> Image name without subfoldername (e.g. "Bildschirmfoto vom 2017-06-02 15-37-42.png")
* Drag & Drop  from pycham's project view into editor --> Not allowed  and no result

**Comment by vsch** [comment] 2017-07-01 03:08
@wotanii, I got ubuntu 16.04 installed and got my dev environment configured so I can debug the plugin. I will update the status within the next day.

**Comment by vsch** [comment] 2017-07-02 01:35
@wotanii, can you please try the EAP Plugin version. There were a few bugs fixed in image paste, file list paste and drag/drop that could be causing this.

I tested it with my dev version and it works as expected on ubuntu 16.04, no cinnamon. I will try this next.

EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.

**Comment by vsch** [comment] 2017-07-07 11:30
@wotanii, I tried this with cinnamon in latest version and this too is working. Can you please get the latest plugin EAP version and let me know if it solves your issue.

**Comment by vsch** [comment] 2017-07-18 17:19
@wotanii, please let me know if this is resolved when you get a chance to try this in the latest released version.

**Comment by wotanii** [comment] 2017-07-23 16:16
Thank you very much for putting work into fixing a "linux-problem". 

___

I changed to EAP. It now says "Installed Version: 2.3.8.8"

I did not notice any changes in the behavior. 

Note: 
* I do not own a licence of Markdown Navigator. I use PyCharm Pro, but a free version of Markdown Navigator
* I did this test on a different machine, than I used when I open this issue. 
* I did not modify the default settings of the plugin.

**Comment by vsch** [comment] 2017-07-23 16:21
@wotanii, pasting images is a licensed feature. This would explain why it does not work for you. You can get a trial license and see all the features enabled and also get the paste images to work here: https://vladsch.com/product/markdown-navigator/try

The licensed version lets you work with markdown files like you do with other languages in the IDE with support for refactoring, navigation, formatting, annotations and intentions.

**Closed** 2017-08-28 15:51 UTC
Labels: bug, in progress
