### ISSUE TITLE
too many element types registered

### ISSUE THREAD

**Issue by ofry** [vsch/idea-multimarkdown#648] opened 2018-11-21 20:45 UTC
Related to https://github.com/vsch/idea-multimarkdown/issues/622

Same issue:

`java.lang.Throwable: Too many element types registered. Out of (short) range. Most of element types (3942) were registered for 'Language: Markdown': FILE, NONE, WHITESPACE, EOL, BLANK_LINE, ABBREVIATION, ABBREVIATION_OPEN, ABBREVIATION_CLOSE, ABBREVIATION_SHORT_TEXT, ABBREVIATION_EXPANDED_TEXT, ABBREVIATED, ABBREVIATED_TEXT, ANCHOR_LINK, BLOCK_QUOTE, BLOCK_QUOTE_MARKER, ASIDE_BLOCK, ASIDE_BLOCK_MARKER, BOLD, BOLD_TEXT, BOLD_MARKER, BULLET_LIST, ...`

**Comment by vsch** [comment] 2018-11-22 03:01
@ofry, I will add an option to completely disable the synthetic attributes, except the basic bold, italic, strike-through. That way if you have a lot of plugins using the syntax highlighting it will not conflict, at least for a while.

**Comment by vsch** [comment] 2018-11-26 18:52
@ofry,

Added option to disable full highlighter attribute generation. Requires restart to take effect.

![highlight-options](https://user-images.githubusercontent.com/10299086/49034561-52ad5800-f180-11e8-9747-8aad4f7a972a.png)

Turning off the `Full highlighter attributes` gives the minimal of 300 attributes. The label right of `Attrs:` shows synthetic/total attributes stats.

EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)

**Comment by ofry** [comment] 2018-11-27 08:20
Still more than 3K attributes registered.

![screenshot_20181127_111850](https://user-images.githubusercontent.com/11790863/49067944-70d58f80-f236-11e8-9033-cf64b000105e.png)

**Comment by vsch** [comment] 2018-11-27 12:48
@ofry, only applied after IDE restart. I will add a restart notification.

> Added option to disable full highlighter attribute generation. **Requires restart to take effect.**

**Comment by vsch** [comment] 2018-11-27 13:38
@ofry, I'll try it on Windows because on OS X I am not seeing the issue. Can't see why the OS would make a different though. (Famous last words)

**Comment by ofry** [comment] 2018-11-27 13:40
It's KUbuntu 18.10 x64

**Comment by vsch** [comment] 2018-11-27 13:42
@ofry, that's better. I haven't launched Windows on parallels for a while. I am sure it would be an hour of updates before I could start working.

**Comment by vsch** [comment] 2018-11-27 14:24
@ofry, cannot duplicate. 

<img width="1173" alt="image" src="https://user-images.githubusercontent.com/10299086/49086941-c2285380-f223-11e8-91f4-58413d6df82d.png">

After restart, is the option selected? If it is then settings are being overwritten.

Otherwise, I will make a new EAP with restart notification which shows up in settings and we'll try again.

If the option is being overwritten then check the file shown before launching the IDE and then after turning it off in the IDE and exiting. It should reflect the selection in settings.

Restart and exit the IDE. If it changes back to true, then something is overwriting the file.

![screenshot_648_1](https://user-images.githubusercontent.com/10299086/49087561-4b8c5580-f225-11e8-8990-abafc1801538.png)

**Comment by ofry** [comment] 2018-11-27 15:13
No, this option is NOT selected.

Project ./.idea/markdown_navigator.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="MarkdownProjectSettings" wasCopied="true">
    <PreviewSettings splitEditorLayout="SPLIT" splitEditorPreview="PREVIEW" useGrayscaleRendering="false" zoomFactor="1.0" maxImageWidth="0" showGitHubPageIfSynced="false" allowBrowsingInPreview="false" synchronizePreviewPosition="true" highlightPreviewType="NONE" highlightFadeOut="5" highlightOnTyping="true" synchronizeSourcePosition="true" verticallyAlignSourceAndPreviewSyncPosition="true" showSearchHighlightsInPreview="false" showSelectionInPreview="true" openRemoteLinks="true" replaceUnicodeEmoji="false" lastLayoutSetsDefault="false">
      <PanelProvider>
        <provider providerId="com.vladsch.idea.multimarkdown.editor.swing.html.panel" providerName="Default - Swing" />
      </PanelProvider>
    </PreviewSettings>
    <ParserSettings gitHubSyntaxChange="false" emojiShortcuts="1" emojiImages="0">
      <PegdownExtensions>
        <option name="ABBREVIATIONS" value="false" />
        <option name="ANCHORLINKS" value="true" />
        <option name="ASIDE" value="false" />
        <option name="ATXHEADERSPACE" value="true" />
        <option name="AUTOLINKS" value="true" />
        <option name="DEFINITIONS" value="false" />
        <option name="DEFINITION_BREAK_DOUBLE_BLANK_LINE" value="false" />
        <option name="FENCED_CODE_BLOCKS" value="true" />
        <option name="FOOTNOTES" value="false" />
        <option name="HARDWRAPS" value="false" />
        <option name="HTML_DEEP_PARSER" value="false" />
        <option name="INSERTED" value="false" />
        <option name="QUOTES" value="false" />
        <option name="RELAXEDHRULES" value="true" />
        <option name="SMARTS" value="false" />
        <option name="STRIKETHROUGH" value="true" />
        <option name="SUBSCRIPT" value="false" />
        <option name="SUPERSCRIPT" value="false" />
        <option name="SUPPRESS_HTML_BLOCKS" value="false" />
        <option name="SUPPRESS_INLINE_HTML" value="false" />
        <option name="TABLES" value="true" />
        <option name="TASKLISTITEMS" value="true" />
        <option name="TOC" value="false" />
        <option name="WIKILINKS" value="true" />
      </PegdownExtensions>
      <ParserOptions>
        <option name="ADMONITION_EXT" value="false" />
        <option name="ATTRIBUTES_EXT" value="false" />
        <option name="COMMONMARK_LISTS" value="true" />
        <option name="DUMMY" value="false" />
        <option name="EMOJI_SHORTCUTS" value="true" />
        <option name="ENUMERATED_REFERENCES_EXT" value="false" />
        <option name="FLEXMARK_FRONT_MATTER" value="false" />
        <option name="GFM_LOOSE_BLANK_LINE_AFTER_ITEM_PARA" value="false" />
        <option name="GFM_TABLE_RENDERING" value="true" />
        <option name="GITBOOK_URL_ENCODING" value="false" />
        <option name="GITHUB_LISTS" value="false" />
        <option name="GITHUB_WIKI_LINKS" value="true" />
        <option name="GITLAB_EXT" value="false" />
        <option name="GITLAB_MATH_EXT" value="false" />
        <option name="GITLAB_MERMAID_EXT" value="false" />
        <option name="HEADER_ID_NO_DUPED_DASHES" value="false" />
        <option name="JEKYLL_FRONT_MATTER" value="false" />
        <option name="MACROS_EXT" value="false" />
        <option name="NO_TEXT_ATTRIBUTES" value="false" />
        <option name="PARSE_HTML_ANCHOR_ID" value="false" />
        <option name="SIM_TOC_BLANK_LINE_SPACER" value="true" />
      </ParserOptions>
    </ParserSettings>
    <HtmlSettings headerTopEnabled="false" headerBottomEnabled="false" bodyTopEnabled="false" bodyBottomEnabled="false" embedUrlContent="false" addPageHeader="true" embedImages="false" embedHttpImages="false" imageUriSerials="false" addDocTypeHtml="true">
      <GeneratorProvider>
        <provider providerId="com.vladsch.idea.multimarkdown.editor.swing.html.generator" providerName="Default Swing HTML Generator" />
      </GeneratorProvider>
      <headerTop />
      <headerBottom />
      <bodyTop />
      <bodyBottom />
    </HtmlSettings>
    <CssSettings previewScheme="UI_SCHEME" cssUri="" isCssUriEnabled="false" isCssUriSerial="false" isCssTextEnabled="false" isDynamicPageWidth="true">
      <StylesheetProvider>
        <provider providerId="com.vladsch.idea.multimarkdown.editor.swing.html.css" providerName="Default Swing Stylesheet" />
      </StylesheetProvider>
      <ScriptProviders />
      <cssText />
      <cssUriHistory />
    </CssSettings>
    <HtmlExportSettings updateOnSave="false" parentDir="" targetDir="" cssDir="" scriptDir="" plainHtml="false" imageDir="" copyLinkedImages="false" imageUniquifyType="0" targetExt="" useTargetExt="false" noCssNoScripts="false" linkToExportedHtml="true" exportOnSettingsChange="true" regenerateOnProjectOpen="false" linkFormatType="HTTP_ABSOLUTE" />
    <LinkMapSettings>
      <textMaps />
    </LinkMapSettings>
  </component>
</project>
```

Global config:

markdown_navigator.local.xml

```
<application>
  <component name="ApplicationLocal" sharedSettingsMigrated="false">
    <DocumentSettings showHtmlPreview="false" verbatimLangInjections="true" htmlLangInjections="true" softWraps="0" iconGutters="true" softWrapAtMargin="false" showEmojiInGutter="false" showBreadcrumbText="true" maxBreadcrumbText="30" previewScrollDelay="500" typingUpdateDelay="500" enableAnnotator="true" hideDisabledButtons="true" hideToolbar="true" disableGifImages="true" codeLikeStyleToggle="true" overrideEditorDragDropHandler="false" toggleStylePunctuations=".,:;!?" htmlMimeMaxImageWidth="100%" htmlMimeFontFamily="" pdfMaxImageWidth="504pt" pdfFontFamily="" detectHtmlOnPaste="false" textSplitLayoutToggle="true" asteriskItalics="true" verticalSplitPreview="false" convertHtmlOnPaste="true" showHeadingID="false" useRenameSpellingFix="true" usePasteHandler="true" includeDirsInCompletion="true" enableLineMarkers="true" tabOverrideTables="true" tabOverrideLists="true" showApplyAllIntentionsEverywhere="false" askHtmlOptionsOnPaste="false" fullHighlightCombinations="false" htmlPasteAddTrailingEol="false" htmlPasteSkipInlineStrong="false" htmlPasteSkipInlineEmphasis="false" htmlPasteSkipInlineCode="false" htmlPasteSkipInlineDel="false" htmlPasteSkipInlineIns="false" htmlPasteSkipInlineSub="false" htmlPasteSkipInlineSup="false" htmlPasteSkipHeading1="false" htmlPasteSkipHeading2="false" htmlPasteSkipHeading3="false" htmlPasteSkipHeading4="false" htmlPasteSkipHeading5="false" htmlPasteSkipHeading6="false" htmlPasteSkipAttributes="false" joinStripPrefix="false" completeRemoteUrlAnchors="false" validateRemoteUrlAnchors="false" validateRemoteUrlLinks="false" simpleStructureView="false" remoteContentCacheExpiration="3600000" remoteContentRequests="4" zoomFactor="1.0" syntaxHighlighting="1" />
    <LicenseInformation licenseType="" showLicenseExpiration="true" showLicenseExpired="true" showFeatureUpdates="true" secureConnection="true">
      <licenseCode />
      <activationCode />
    </LicenseInformation>
    <Notifications showFeatureUpdates="true" />
    <DebugSettings debugFormatText="false" debugCombinationColors="false" debugTestFileDirectory="" generateParserExceptions="false" enableJavaFxPreviewDebugging="false" javaFxPreviewResourceUseSerials="true" flexmarkSpecExampleRendering="0" flexmarkSpecExampleRenderHtml="false" parsingTimeout="100" preferencesDialogWidth="1000" preferencesDialogHeight="1000" javaFxPreviewDebugPort="51742" lastSettingsImport="" javaFxPreviewResourceURL="" javaFxPreviewResourceDir="" translateAutoDetect="false" remoteInvalidUntilFetched="false" outputRemoteFetchExceptions="false" translateFrom="de" translateTo="en" translateKey="">
      <javaFxPreviewResourceDirHistory />
      <debugTestFileDirectoryHistory />
      <javaFxPreviewResourceURLHistory />
    </DebugSettings>
    <FailedInBuild scratchFileServiceFailed="" fxPreviewFailedBuild="" lightParserFailedBuild="" />
    <WasShown licensedAvailable="true" lastFeatureUpdateVersion="" lastLicensedAvailableVersion="2.7.0.2" javaFxAvailable="false" jekyllFrontMatter="false" gitHubSyntaxChange="false" />
  </component>
</application>
```

markdown_navigator.shared.xml:
```
<application>
  <component name="Markdown Navigator">
    <PreviewSettings splitEditorLayout="SPLIT" splitEditorPreview="PREVIEW" useGrayscaleRendering="false" zoomFactor="1.0" maxImageWidth="0" showGitHubPageIfSynced="false" allowBrowsingInPreview="false" synchronizePreviewPosition="true" highlightPreviewType="NONE" highlightFadeOut="5" highlightOnTyping="true" synchronizeSourcePosition="true" verticallyAlignSourceAndPreviewSyncPosition="true" showSearchHighlightsInPreview="false" showSelectionInPreview="true" openRemoteLinks="true" replaceUnicodeEmoji="false" lastLayoutSetsDefault="false">
      <PanelProvider>
        <provider providerId="com.vladsch.idea.multimarkdown.editor.swing.html.panel" providerName="Default - Swing" />
      </PanelProvider>
    </PreviewSettings>
    <ParserSettings gitHubSyntaxChange="false" emojiShortcuts="1" emojiImages="0">
      <PegdownExtensions>
        <option name="ABBREVIATIONS" value="false" />
        <option name="ANCHORLINKS" value="true" />
        <option name="ASIDE" value="false" />
        <option name="ATXHEADERSPACE" value="true" />
        <option name="AUTOLINKS" value="true" />
        <option name="DEFINITIONS" value="false" />
        <option name="DEFINITION_BREAK_DOUBLE_BLANK_LINE" value="false" />
        <option name="FENCED_CODE_BLOCKS" value="true" />
        <option name="FOOTNOTES" value="false" />
        <option name="HARDWRAPS" value="false" />
        <option name="HTML_DEEP_PARSER" value="false" />
        <option name="INSERTED" value="false" />
        <option name="QUOTES" value="false" />
        <option name="RELAXEDHRULES" value="true" />
        <option name="SMARTS" value="false" />
        <option name="STRIKETHROUGH" value="true" />
        <option name="SUBSCRIPT" value="false" />
        <option name="SUPERSCRIPT" value="false" />
        <option name="SUPPRESS_HTML_BLOCKS" value="false" />
        <option name="SUPPRESS_INLINE_HTML" value="false" />
        <option name="TABLES" value="true" />
        <option name="TASKLISTITEMS" value="true" />
        <option name="TOC" value="false" />
        <option name="WIKILINKS" value="true" />
      </PegdownExtensions>
      <ParserOptions>
        <option name="ADMONITION_EXT" value="false" />
        <option name="ATTRIBUTES_EXT" value="false" />
        <option name="COMMONMARK_LISTS" value="true" />
        <option name="DUMMY" value="false" />
        <option name="EMOJI_SHORTCUTS" value="true" />
        <option name="ENUMERATED_REFERENCES_EXT" value="false" />
        <option name="FLEXMARK_FRONT_MATTER" value="false" />
        <option name="GFM_LOOSE_BLANK_LINE_AFTER_ITEM_PARA" value="false" />
        <option name="GFM_TABLE_RENDERING" value="true" />
        <option name="GITBOOK_URL_ENCODING" value="false" />
        <option name="GITHUB_LISTS" value="false" />
        <option name="GITHUB_WIKI_LINKS" value="true" />
        <option name="HEADER_ID_NO_DUPED_DASHES" value="false" />
        <option name="JEKYLL_FRONT_MATTER" value="false" />
        <option name="NO_TEXT_ATTRIBUTES" value="false" />
        <option name="PARSE_HTML_ANCHOR_ID" value="false" />
        <option name="SIM_TOC_BLANK_LINE_SPACER" value="true" />
      </ParserOptions>
    </ParserSettings>
    <HtmlSettings headerTopEnabled="false" headerBottomEnabled="false" bodyTopEnabled="false" bodyBottomEnabled="false" embedUrlContent="false" addPageHeader="true" embedImages="false" embedHttpImages="false" imageUriSerials="false">
      <GeneratorProvider>
        <provider providerId="com.vladsch.idea.multimarkdown.editor.swing.html.generator" providerName="Default Swing HTML Generator" />
      </GeneratorProvider>
      <headerTop />
      <headerBottom />
      <bodyTop />
      <bodyBottom />
    </HtmlSettings>
    <CssSettings previewScheme="UI_SCHEME" cssUri="" isCssUriEnabled="false" isCssUriSerial="true" isCssTextEnabled="false" isDynamicPageWidth="true">
      <StylesheetProvider>
        <provider providerId="com.vladsch.idea.multimarkdown.editor.swing.html.css" providerName="Default Swing Stylesheet" />
      </StylesheetProvider>
      <ScriptProviders />
      <cssText />
      <cssUriHistory />
    </CssSettings>
    <HtmlExportSettings updateOnSave="false" parentDir="" targetDir="" cssDir="" scriptDir="" plainHtml="false" imageDir="" copyLinkedImages="false" imageUniquifyType="0" targetExt="" useTargetExt="false" noCssNoScripts="false" linkToExportedHtml="true" exportOnSettingsChange="true" regenerateOnProjectOpen="false" linkFormatType="HTTP_ABSOLUTE" />
    <LinkMapSettings>
      <textMaps />
    </LinkMapSettings>
  </component>
</application>
```

**Comment by vsch** [comment] 2018-11-27 15:31
@ofry, this is absolutely strange. The highlighter attributes use this setting to figure out if all should be generated. I am stumped. The only thing I can think of is that there is an installation issue with an old class file being used.

Normally the zips/jars are not expanded but sometimes (for debugging for sure) the IDE will extract some classes out of the jar under the plugin directory and then they have priority over classes in the jars. 

Not sure where the directory is on UBuntu, but on OS X it is in `~/Library/Application Support`:

![image](https://user-images.githubusercontent.com/10299086/49092141-52b86100-f22f-11e8-9120-62dca987d62d.png)

If you see `classes` or `META-INF` subdirectories in this directory then you should delete them.

As a last resort can you un-install the plugin and re-install it. If it a problem with old class files then a new plugin version will have the same issue.

**Comment by ofry** [comment] 2018-11-27 15:58
Your image not shown there...

**Comment by vsch** [comment] 2018-11-27 15:59
@ofry, can you try refreshing the page. It is on github: https://user-images.githubusercontent.com/10299086/49092141-52b86100-f22f-11e8-9120-62dca987d62d.png

**Comment by ofry** [comment] 2018-11-27 16:02
Can you try to open this image in Firefox? It not open there...

**Comment by ofry** [comment] 2018-11-27 16:09
And which IDE you're using? I'm using IntelliJ IDEA

**Comment by vsch** [comment] 2018-11-27 16:12
@ofry, firefox has issues. This file I opened in firefox but if the issue is with GitHub uploads then the same issue will come up.

![49092141-52b86100-f22f-11e8-9120-62dca987d62d copy](https://user-images.githubusercontent.com/10299086/49094871-3d463580-f235-11e8-9412-6e3dd771060a.png)

**Comment by vsch** [comment] 2018-11-27 16:14
@ofry, I am using IDEA community and IntelliJ and others. I don't think it makes a difference. Your issue is at a different level. Something is wrong with the plugin installation on your system or something else is causing the issue.

**Comment by ofry** [comment] 2018-11-27 16:31
Could you add option to regenerate attributes every IDE start?

**Comment by vsch** [comment] 2018-11-27 16:33
@ofry, this is exactly what it does based on the setting full attribute combinations. The reason it needs a restart is because attribute combinations are generated early in the startup sequence.

The issue on your system is something else. Can you please check the IDE error log to see if there are exceptions.

**Comment by ofry** [comment] 2018-11-27 16:42
@vsch can't it be cached somewhere? Maybe by another plugin? Then "regenerate" only basic attributes can help.

**Comment by vsch** [comment] 2018-11-27 16:45
@ofry, attributes are not cached but registered with the IDE API on startup. I'll make another release which will show restart status and have updated classes. Maybe it will be solved then. Like I said, I do not see how this can happen unless there is something wrong with the installation. It is very basic functionality to get a property and test it for true/false. Other than having an old class file which does not check for the setting, I cannot see how this can happen.

**Comment by vsch** [comment] 2018-11-28 15:17
@ofry, thank you the log is perfect and it shows the problem. It appears that when setting is read for the `LexParserState` it is always true. I will change the initialization of attributes to happen later in the initialization sequence. I am guessing that the settings are not available when it is being initialized in the current implementation.

Sorry for the hassle and thank you for your effort of sticking with it and providing debug information. I will have it fixed shortly.

**Comment by vsch** [comment] 2018-11-29 05:02
@ofry, it is resolved. The issue was with a bug that caused odd-ball initialization of settings. It is now fixed, along with a few other nasty performance bugs. Thank you very much for your persistent effort. I want to apologize for taking this long to fix it. Please contact me by e-mail in my GitHub profile so I can send you a complimentary license. You have helped find a real PITA bug and I would like you to enjoy a full version of the plugin.

EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)

**Comment by ofry** [comment] 2018-11-29 05:46
@vsch I have sent you e-mail just now.

**Closed** 2019-02-03 22:43 UTC
Labels: enhancement, fix available, fixed for next release
