### ISSUE TITLE
Typographical Error in PHPStorm Preferences > Editor > Code Style > Markdown

### ISSUE THREAD

**Issue by stevecw** [vsch/idea-multimarkdown#542] opened 2017-12-17 21:13 UTC
What steps will reproduce the problem?
1. Open PhpStorm
2. View the Preferences > Editor > Code Style > Markdown dialog box
3. Scroll to bottom of the window
4. Observe that **Alignt Columns** makes no sense

What is the expected result?
I expect to see either **Aligned Columns** or **Column Alignment** _(whichever makes more sense for the intended context)_

What happens instead?
I see text that looks almost like an abbreviation but there is more than enough room to ***not*** require the first word to be abbreviated, so I am assuming it is a typographical error.

Please see attached screenshot.
<img width="669" alt="storm typo" src="https://user-images.githubusercontent.com/26632419/34083832-6a2bfcfc-e32b-11e7-98f6-d6c20bc00376.png">

**Comment by vsch** [comment] 2018-01-13 15:28
@stevecw, thank you for catching it. It should be "Align Columns" which should be read as: on table format Align Columns.

It will be fixed in the next release.

**Comment by vsch** [comment] 2018-01-15 00:41
EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.

**Closed** 2018-03-16 14:36 UTC
Labels: fix available, fixed for next release, usability
